# Generated by Django 6.0.2 on 2026-04-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembangkit',
            name='jenis',
            field=models.CharField(choices=[('PLTA', 'PLTA — Tenaga Air'), ('PLTB', 'PLTB — Tenaga Bayu'), ('PLTD', 'PLTD — Tenaga Diesel'), ('PLTU', 'PLTU — Tenaga Uap'), ('PLTG', 'PLTG — Tenaga Gas'), ('PLTGU', 'PLTGU — Gas & Uap'), ('PLTS', 'PLTS — Tenaga Surya'), ('LAIN', 'Lainnya')], default='PLTD', max_length=10, verbose_name='Jenis'),
        ),
    ]
