# Generated by Django 6.0.2 on 2026-04-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0002_add_jenis_to_pembangkit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('mw', models.FloatField(null=True)),
                ('mvar', models.FloatField(null=True)),
                ('frekuensi', models.FloatField(null=True)),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('pembangkit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snaps', to='opsis.pembangkit')),
            ],
            options={
                'verbose_name': 'Snapshot Live',
                'verbose_name_plural': 'Snapshots Live',
                'ordering': ['-waktu'],
            },
        ),
        migrations.CreateModel(
            name='SnapUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('mw', models.FloatField(null=True)),
                ('mvar', models.FloatField(null=True)),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='opsis.snaplive')),
            ],
            options={
                'verbose_name': 'Unit Snapshot',
                'verbose_name_plural': 'Unit Snapshots',
            },
        ),
        migrations.AddIndex(
            model_name='snaplive',
            index=models.Index(fields=['pembangkit', '-waktu'], name='opsis_snapl_pembang_976232_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snaplive',
            unique_together={('pembangkit', 'waktu')},
        ),
        migrations.AlterUniqueTogether(
            name='snapunit',
            unique_together={('snap', 'nama')},
        ),
    ]
