# Generated by Django 6.0.2 on 2026-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0003_snaplive_snapunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(db_index=True, unique=True)),
                ('hz', models.FloatField()),
            ],
            options={
                'verbose_name': 'Snapshot Frekuensi',
                'verbose_name_plural': 'Snapshots Frekuensi',
                'ordering': ['-waktu'],
            },
        ),
    ]
