# Generated by Django 6.0.2 on 2026-07-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0005_trafo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapFreqArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('sultra', 'Sultra — GI Kendari New'), ('sulteng', 'Sulteng — GI Talise 150'), ('baubau', 'Baubau — GI Baubau'), ('luwuk', 'Luwuk — GI Luwuk')], db_index=True, max_length=10)),
                ('waktu', models.DateTimeField(db_index=True)),
                ('hz', models.FloatField()),
            ],
            options={
                'verbose_name': 'Snapshot Frekuensi Area',
                'verbose_name_plural': 'Snapshots Frekuensi Area',
                'ordering': ['-waktu'],
                'unique_together': {('area', 'waktu')},
            },
        ),
    ]
