# Generated by Django 6.0.2 on 2026-07-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0008_remove_snaptrafo_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembangkit',
            name='kode_kit',
            field=models.CharField(blank=True, help_text='Kode KIT_REALTIME yang dibaca. Kosongkan jika sama dengan Kode.', max_length=20, verbose_name='Kode KIT (MSSQL)'),
        ),
        migrations.AddField(
            model_name='pembangkit',
            name='unit_list',
            field=models.CharField(blank=True, help_text='Daftar unit dipisah koma, mis. UNIT1,UNIT2,UNIT3. Kosongkan untuk memakai semua unit (UNIT1-UNIT8).', max_length=100, verbose_name='Unit yang Dipakai'),
        ),
    ]
