# Generated by Django 6.0.2 on 2026-07-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0009_pembangkit_kode_kit_pembangkit_unit_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="HopPembangkit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(max_length=120, verbose_name="Nama Pembangkit"),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[("batubara", "Batu Bara"), ("bbm", "BBM")],
                        db_index=True,
                        max_length=10,
                        verbose_name="Kategori Bahan Bakar",
                    ),
                ),
                (
                    "sistem",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sulbagsel", "Sulbagsel"),
                            ("Sulutgo", "Sulutgo"),
                            ("Baubau", "Baubau"),
                        ],
                        max_length=20,
                        verbose_name="Sistem",
                    ),
                ),
                (
                    "aset",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Aset / Pengelola"
                    ),
                ),
                (
                    "dmn_mw",
                    models.FloatField(blank=True, null=True, verbose_name="DMN (MW)"),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "HOP — Pembangkit",
                "verbose_name_plural": "HOP — Pembangkit",
                "ordering": ["kategori", "urutan", "nama"],
                "unique_together": {("nama", "kategori")},
            },
        ),
        migrations.CreateModel(
            name="HopSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(db_index=True)),
                ("hop", models.FloatField(null=True, verbose_name="HOP (hari)")),
                (
                    "pembangkit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hop_snaps",
                        to="opsis.hoppembangkit",
                    ),
                ),
            ],
            options={
                "verbose_name": "HOP — Snapshot Harian",
                "verbose_name_plural": "HOP — Snapshot Harian",
                "ordering": ["-tanggal"],
                "indexes": [
                    models.Index(
                        fields=["pembangkit", "-tanggal"],
                        name="opsis_hopsn_pembang_1e8b58_idx",
                    )
                ],
                "unique_together": {("pembangkit", "tanggal")},
            },
        ),
    ]
