# Generated by Django 6.0.2 on 2026-07-25 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0010_hoppembangkit_hopsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pembangkit",
            name="data_keterangan",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Keterangan Ketidaksesuaian",
            ),
        ),
        migrations.AddField(
            model_name="pembangkit",
            name="data_tidak_sesuai",
            field=models.BooleanField(default=False, verbose_name="Data Tidak Sesuai"),
        ),
        migrations.AddField(
            model_name="pembangkit",
            name="ditandai_oleh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ditandai Oleh",
            ),
        ),
        migrations.AddField(
            model_name="pembangkit",
            name="ditandai_pada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ditandai Pada"
            ),
        ),
    ]
