# Generated by Django 6.0.2 on 2026-07-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0011_pembangkit_data_keterangan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pembangkit",
            name="supply",
            field=models.CharField(
                blank=True,
                choices=[("netto", "Netto"), ("gross", "Gross")],
                default="",
                help_text="Netto / Gross. Tampil sebagai label kecil di kartu dashboard. Kosongkan bila tidak ingin menampilkan label.",
                max_length=5,
                verbose_name="Tipe Supply",
            ),
        ),
    ]
