# Generated by Django 6.0.2 on 2026-08-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0012_pembangkit_supply"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapFreqRT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waktu", models.DateTimeField(db_index=True, unique=True)),
                ("hz", models.FloatField()),
            ],
            options={
                "verbose_name": "Snapshot Frekuensi RT",
                "verbose_name_plural": "Snapshot Frekuensi RT",
                "ordering": ["-waktu"],
            },
        ),
    ]
