# Generated by Django 6.0.2 on 2026-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0013_snapfreqrt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafo',
            name='sumber_filter_kolom',
            field=models.CharField(blank=True, default='', help_text='Kolom penanda titik. Mode Baris: kolom yang dicocokkan dengan Tag P/Q/V/I (mis. ANALOG). Mode Kolom: kolom untuk memilih baris (mis. BAY).', max_length=50, verbose_name='Kolom Kunci'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_filter_nilai',
            field=models.CharField(blank=True, default='', help_text='Hanya untuk mode Kolom — nilai yang dicari pada Kolom Kunci.', max_length=100, verbose_name='Nilai Kunci (mode Kolom)'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_i',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tag/Kolom I'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_kolom_nilai',
            field=models.CharField(blank=True, default='VALUE', help_text='Hanya untuk mode Baris — kolom berisi angkanya. Umumnya VALUE.', max_length=50, verbose_name='Kolom Nilai (mode Baris)'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_mode',
            field=models.CharField(choices=[('baris', 'Baris — satu titik per baris (kolom kunci + kolom nilai)'), ('kolom', 'Kolom — satu baris berisi kolom P/Q/V/I')], default='baris', max_length=10, verbose_name='Bentuk Tabel Sumber'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_p',
            field=models.CharField(blank=True, default='', help_text='Mode Baris: nilai kunci titik P. Mode Kolom: nama kolom P. Kosongkan bila metrik ini tidak ada di tabel sumber.', max_length=100, verbose_name='Tag/Kolom P'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_q',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tag/Kolom Q'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_tabel',
            field=models.CharField(blank=True, default='', help_text='Kosongkan untuk memakai ALL_TRANS_DATA (default). Contoh: dbo.ANALOG_RT', max_length=100, verbose_name='Tabel Sumber Pengganti'),
        ),
        migrations.AddField(
            model_name='trafo',
            name='sumber_v',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tag/Kolom V'),
        ),
    ]
