# Generated by Django 6.0.2 on 2026-08-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0015_trafo_override_wotu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembangkit',
            name='dmp_key',
            field=models.CharField(blank=True, help_text='Nilai pada Kolom Kunci KIT_DMP yang menandai pembangkit ini (mis. isi KIT). Kosongkan untuk memakai Kode KIT / Kode.', max_length=50, verbose_name='Nilai Kunci KIT_DMP'),
        ),
        migrations.AddField(
            model_name='pembangkit',
            name='dmp_kolom_dmn',
            field=models.CharField(blank=True, default='', help_text='Nama kolom KIT_DMP berisi Daya Mampu Netto (MW). Kosongkan bila DMN tidak tersedia.', max_length=50, verbose_name='Kolom DMN'),
        ),
        migrations.AddField(
            model_name='pembangkit',
            name='dmp_kolom_dmp',
            field=models.CharField(blank=True, default='', help_text='Nama kolom KIT_DMP berisi Daya Mampu Pasok (MW). Kosongkan bila DMP tidak tersedia.', max_length=50, verbose_name='Kolom DMP'),
        ),
    ]
