# Generated by Django 6.0.2 on 2026-08-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0016_pembangkit_dmp_key_pembangkit_dmp_kolom_dmn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembangkit',
            name='dmp_key',
            field=models.CharField(blank=True, help_text='Nilai pada Kolom Kunci KIT_DMP yang menandai pembangkit ini (mis. isi KIT). Pisahkan dengan koma untuk menggabungkan beberapa baris, contoh: POSO2A_U1,POSO2A_U2. Kosongkan untuk memakai Kode KIT / Kode.', max_length=200, verbose_name='Nilai Kunci KIT_DMP'),
        ),
    ]
