# Generated by Django 6.0.2 on 2026-08-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0017_alter_pembangkit_dmp_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrakiraanBeban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('menit', models.PositiveSmallIntegerField(help_text='Menit sejak 00:00 waktu lokal (0–1439). Grid 30 menit: 0, 30, 60, …')),
                ('mw', models.FloatField()),
                ('sumber', models.CharField(default='spreadsheet', help_text='Asal data, mis. nama sheet / "spreadsheet" / "upload".', max_length=50)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prakiraan Beban',
                'verbose_name_plural': 'Prakiraan Beban',
                'ordering': ['-tanggal', 'menit'],
                'indexes': [models.Index(fields=['tanggal', 'menit'], name='opsis_praki_tanggal_2ea08e_idx')],
                'unique_together': {('tanggal', 'menit')},
            },
        ),
    ]
