# Generated by Django 6.0.2 on 2026-08-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0018_prakiraanbeban"),
    ]

    operations = [
        migrations.AddField(
            model_name="pembangkit",
            name="peta_x",
            field=models.FloatField(
                blank=True,
                help_text="0–100, persen dari kiri peta. Kosongkan untuk posisi bawaan.",
                null=True,
                verbose_name="Posisi Peta X (%)",
            ),
        ),
        migrations.AddField(
            model_name="pembangkit",
            name="peta_y",
            field=models.FloatField(
                blank=True,
                help_text="0–100, persen dari atas peta. Kosongkan untuk posisi bawaan.",
                null=True,
                verbose_name="Posisi Peta Y (%)",
            ),
        ),
    ]
