# Generated by Django 6.0.2 on 2026-08-20 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0019_pembangkit_peta_x_pembangkit_peta_y"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModePemeliharaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=False,
                        help_text="Bila dicentang, semua halaman /opsis/ diganti halaman pemeliharaan.",
                        verbose_name="Aktifkan Mode Pemeliharaan",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        default="OPSIS Sedang Dalam Pemeliharaan",
                        help_text="Judul besar yang tampil di halaman pemeliharaan.",
                        max_length=120,
                        verbose_name="Judul",
                    ),
                ),
                (
                    "pesan",
                    models.TextField(
                        default="Dashboard OPSIS untuk sementara tidak dapat diakses karena koneksi ke server data SCADA (MSSQL) belum tersedia. Halaman akan dibuka kembali setelah koneksi siap.",
                        help_text="Penjelasan singkat untuk pengguna.",
                        verbose_name="Pesan",
                    ),
                ),
                (
                    "perkiraan_selesai",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opsional. Kosongkan bila belum ada perkiraan waktu.",
                        null=True,
                        verbose_name="Perkiraan Selesai",
                    ),
                ),
                (
                    "boleh_superuser",
                    models.BooleanField(
                        default=True,
                        help_text="Bila dicentang, superuser tetap dapat membuka /opsis/ untuk pengujian (dengan pita penanda di atas halaman). Hilangkan centang untuk menutup OPSIS bagi semua orang tanpa kecuali.",
                        verbose_name="Superuser Tetap Bisa Masuk",
                    ),
                ),
                (
                    "diubah_pada",
                    models.DateTimeField(auto_now=True, verbose_name="Diubah Pada"),
                ),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diubah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mode Pemeliharaan OPSIS",
                "verbose_name_plural": "Mode Pemeliharaan OPSIS",
            },
        ),
    ]
