# Generated by Django 6.0.2 on 2026-08-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0020_modepemeliharaan"),
    ]

    operations = [
        migrations.AddField(
            model_name="pembangkit",
            name="tampil_di_peta",
            field=models.BooleanField(
                default=True,
                help_text="Hilangkan centang untuk menyembunyikan ikon pembangkit ini dari Peta Pembangkit (mis. hanya menampilkan pembangkit berbeban besar). Pembangkitnya tetap masuk tabel daya di sebelah peta.",
                verbose_name="Tampilkan Ikon di Peta",
            ),
        ),
    ]
