# Generated by Django 6.0.2 on 2026-08-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0021_pembangkit_tampil_di_peta"),
    ]

    operations = [
        migrations.CreateModel(
            name="KelompokPeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        help_text='Tampil sebagai keterangan di bawah ikon, mis. "Kompleks Tello".',
                        max_length=80,
                        verbose_name="Nama Kelompok",
                    ),
                ),
                (
                    "keterangan",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Opsional. Tampil saat kursor diarahkan ke ikon.",
                        max_length=200,
                        verbose_name="Keterangan",
                    ),
                ),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("PLTA", "PLTA — Tenaga Air"),
                            ("PLTB", "PLTB — Tenaga Bayu"),
                            ("PLTD", "PLTD — Tenaga Diesel"),
                            ("PLTU", "PLTU — Tenaga Uap"),
                            ("PLTG", "PLTG — Tenaga Gas"),
                            ("PLTGU", "PLTGU — Gas & Uap"),
                            ("PLTS", "PLTS — Tenaga Surya"),
                            ("LAIN", "Lainnya"),
                        ],
                        default="LAIN",
                        help_text="Menentukan gambar dan warna ikon kelompok.",
                        max_length=10,
                        verbose_name="Ikon Jenis",
                    ),
                ),
                (
                    "peta_x",
                    models.FloatField(
                        default=50,
                        help_text="0–100, persen dari kiri peta.",
                        verbose_name="Posisi Peta X (%)",
                    ),
                ),
                (
                    "peta_y",
                    models.FloatField(
                        default=50,
                        help_text="0–100, persen dari atas peta.",
                        verbose_name="Posisi Peta Y (%)",
                    ),
                ),
                (
                    "tampil_di_peta",
                    models.BooleanField(default=True, verbose_name="Tampilkan di Peta"),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                ("diubah_pada", models.DateTimeField(auto_now=True)),
                (
                    "anggota",
                    models.ManyToManyField(
                        blank=True,
                        related_name="kelompok_peta",
                        to="opsis.pembangkit",
                        verbose_name="Pembangkit Anggota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kelompok Peta",
                "verbose_name_plural": "Kelompok Peta",
                "ordering": ["nama"],
            },
        ),
    ]
