# Generated by Django 6.0.2 on 2026-08-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0022_kelompokpeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='KolomEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kolom')),
                ('keterangan', models.TextField(blank=True, default='', help_text='Teks kecil di bawah judul kolom — menjelaskan skema apa saja yang masuk kolom ini.', verbose_name='Keterangan')),
                ('warna', models.CharField(default='#3987e5', help_text='Kode warna garis di kiri judul kolom, mis. #3987e5.', max_length=20, verbose_name='Warna Aksen')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kolom EWS',
                'verbose_name_plural': 'Kolom EWS',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='TitikEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Titik / Lokasi Rele')),
                ('skema', models.CharField(choices=[('UVLS', 'UVLS — Under Voltage Load Shedding'), ('OVTS', 'OVTS — Over Voltage Transmission Shedding'), ('OVCS', 'OVCS — Over Voltage Capacitor Switching'), ('UVRS', 'UVRS — Under Voltage Reactor Switching'), ('OFGS', 'OFGS — Over Frequency Generator Shedding'), ('UFLS', 'UFLS — Under Frequency Load Shedding'), ('OLS', 'OLS — Over Load Shedding'), ('OGS', 'OGS — Over Generation Shedding'), ('ADS', 'ADS — Anti Discharge Scheme'), ('UPLS', 'UPLS — Under Power Load Shedding'), ('ISLAND', 'ISLAND — Islanding Scheme')], max_length=10, verbose_name='Jenis Skema')),
                ('sistem', models.CharField(default='Sulbagsel', help_text='Mis. Sulbagsel / BauBau / Luwuk. Dipakai sebagai filter di halaman EWS.', max_length=50, verbose_name='Sistem')),
                ('subsistem', models.CharField(blank=True, default='', max_length=50, verbose_name='Subsistem')),
                ('nomor', models.CharField(blank=True, default='', max_length=10, verbose_name='No. Berkas')),
                ('kode', models.CharField(blank=True, default='', max_length=20, verbose_name='Kode Skema')),
                ('target', models.TextField(blank=True, default='', help_text='Beban/pembangkit yang dilepas saat skema bekerja.', verbose_name='Target Kerja')),
                ('time_delay', models.CharField(blank=True, default='', max_length=30, verbose_name='Time Delay')),
                ('status_skema', models.CharField(choices=[('aktif', 'Terpasang & Aktif'), ('nonaktif', 'Terpasang, Tidak Aktif'), ('rencana', 'Rencana')], default='aktif', max_length=10, verbose_name='Status Skema')),
                ('catatan', models.TextField(blank=True, default='', help_text='Satu catatan per baris. Ditampilkan bertanda bendera di panel detail.', verbose_name='Catatan / Ketidaksesuaian')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('besaran', models.CharField(choices=[('v', 'Tegangan (kV)'), ('f', 'Frekuensi (Hz)'), ('i', 'Arus (A)'), ('p', 'Daya (MW)')], default='v', max_length=2, verbose_name='Besaran Ukur')),
                ('satuan', models.CharField(blank=True, default='', help_text='Kosongkan untuk memakai satuan bawaan besaran (kV/Hz/A/MW).', max_length=10, verbose_name='Satuan')),
                ('nominal', models.FloatField(blank=True, help_text='Mis. 150 untuk bus 150 kV, 50 untuk frekuensi. Kosongkan untuk arus.', null=True, verbose_name='Nilai Nominal')),
                ('setting', models.FloatField(blank=True, help_text='Vset/Fset/Iset. Kosongkan bila belum tercantum — kartu ditandai "setting belum diisi" dan margin tidak dihitung.', null=True, verbose_name='Setting Rele')),
                ('arah', models.CharField(choices=[('bawah', 'Ambang bawah — skema bekerja saat nilai turun melewati setting'), ('atas', 'Ambang atas — skema bekerja saat nilai naik melewati setting')], default='bawah', max_length=5, verbose_name='Arah Kerja')),
                ('ambang_waspada', models.FloatField(blank=True, help_text='Kosongkan untuk memakai bawaan: 3% Vn (tegangan), 0,15 Hz (frekuensi), 5% I Set (arus), 10% ambang (daya). Tegangan/arus/daya diisi dalam pecahan (0.03 = 3%), frekuensi dalam Hz.', null=True, verbose_name='Ambang Waspada')),
                ('sumber_tabel', models.CharField(blank=True, default='', help_text='Kosongkan bila titik ini belum termonitor. Contoh: dbo.KIT_REALTIME', max_length=100, verbose_name='Tabel Sumber (MSSQL)')),
                ('sumber_kolom_nilai', models.CharField(blank=True, default='VALUE', help_text='Kolom berisi angka yang dibaca. Umumnya VALUE.', max_length=50, verbose_name='Kolom Nilai')),
                ('sumber_kolom_kunci', models.CharField(blank=True, default='', help_text='Kolom penanda titik, mis. ANALOG atau KIT. Kosongkan bila tabelnya hanya berisi satu baris (nilai diambil dari baris pertama).', max_length=50, verbose_name='Kolom Kunci')),
                ('sumber_nilai_kunci', models.CharField(blank=True, default='', help_text='Nilai yang dicari pada Kolom Kunci, mis. FREQ_MKS.', max_length=100, verbose_name='Nilai Kunci')),
                ('faktor_skala', models.FloatField(default=1.0, help_text='Nilai MSSQL dikalikan angka ini. Mis. 0.001 bila historian menyimpan Volt sementara halaman menampilkan kV.', verbose_name='Faktor Skala')),
                ('kolom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titik', to='opsis.kolomews', verbose_name='Kolom Parameter')),
            ],
            options={
                'verbose_name': 'Titik EWS',
                'verbose_name_plural': 'Titik EWS',
                'ordering': ['kolom__urutan', 'urutan', 'nama'],
            },
        ),
    ]
