# Generated by Django 6.0.2 on 2026-09-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0023_kolomews_titikews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KartuPadam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=False,
                        help_text="Bila dicentang, kartu Total Padam muncul di dashboard OPSIS. Menghilangkan centang menyembunyikannya dari semua layar dalam beberapa detik, tanpa perlu reload.",
                        verbose_name="Tampilkan Kartu Total Padam",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        default="Total Padam",
                        help_text='Teks kecil di atas angka, mis. "Total Padam".',
                        max_length=60,
                        verbose_name="Judul Kartu",
                    ),
                ),
                (
                    "satuan",
                    models.CharField(
                        blank=True,
                        default="MW",
                        help_text="Ditampilkan di belakang angka. Kosongkan bila angkanya tanpa satuan (mis. jumlah penyulang).",
                        max_length=10,
                        verbose_name="Satuan",
                    ),
                ),
                (
                    "desimal",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Banyak angka di belakang koma. Isi 0 untuk bilangan bulat (cocok untuk mode Hitung).",
                        verbose_name="Jumlah Desimal",
                    ),
                ),
                (
                    "warna",
                    models.CharField(
                        default="#f87171",
                        help_text="Warna angka dan garis tepi kartu, mis. #f87171.",
                        max_length=20,
                        verbose_name="Warna Aksen",
                    ),
                ),
                (
                    "keterangan",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teks kecil di bawah angka. Kosongkan untuk memakai keterangan bawaan (jumlah baris sumber yang terbaca).",
                        max_length=120,
                        verbose_name="Keterangan",
                    ),
                ),
                (
                    "agregasi",
                    models.CharField(
                        choices=[
                            (
                                "jumlah",
                                "Jumlah — SUM kolom nilai dari semua baris yang cocok",
                            ),
                            (
                                "hitung",
                                "Hitung — COUNT baris yang cocok (kolom nilai tidak dipakai)",
                            ),
                            (
                                "nilai",
                                "Nilai tunggal — TOP 1 kolom nilai dari baris yang cocok",
                            ),
                        ],
                        default="jumlah",
                        max_length=10,
                        verbose_name="Cara Menghitung",
                    ),
                ),
                (
                    "sumber_tabel",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Kosongkan bila sumbernya belum ditentukan — kartu tampil "sumber belum diatur". Contoh: dbo.PADAM_RT',
                        max_length=100,
                        verbose_name="Tabel Sumber (MSSQL)",
                    ),
                ),
                (
                    "sumber_kolom_nilai",
                    models.CharField(
                        blank=True,
                        default="VALUE",
                        help_text="Kolom berisi angka yang dijumlahkan/dibaca. Tidak dipakai pada mode Hitung.",
                        max_length=50,
                        verbose_name="Kolom Nilai",
                    ),
                ),
                (
                    "sumber_kolom_kunci",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kolom penyaring baris, mis. ANALOG atau STATUS. Kosongkan untuk memakai SELURUH isi tabel.",
                        max_length=50,
                        verbose_name="Kolom Kunci",
                    ),
                ),
                (
                    "sumber_nilai_kunci",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nilai yang dicari pada Kolom Kunci. Pisahkan dengan koma untuk beberapa titik sekaligus, mis. PADAM_MKS,PADAM_KDI. Dikosongkan berarti tanpa penyaring.",
                        max_length=255,
                        verbose_name="Nilai Kunci",
                    ),
                ),
                (
                    "faktor_skala",
                    models.FloatField(
                        default=1.0,
                        help_text="Hasil dikalikan angka ini. Mis. 0.001 bila historian menyimpan kW sementara kartu menampilkan MW.",
                        verbose_name="Faktor Skala",
                    ),
                ),
                (
                    "diubah_pada",
                    models.DateTimeField(auto_now=True, verbose_name="Diubah Pada"),
                ),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diubah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kartu Total Padam",
                "verbose_name_plural": "Kartu Total Padam",
            },
        ),
    ]
