# Generated by Django 6.0.2 on 2026-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0024_kartupadam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantauanKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='KIT Terpilih', help_text='Tampil sebagai judul kartu kecil dan chart-nya di dashboard.', max_length=80, verbose_name='Judul Kartu')),
                ('warna', models.CharField(default='#38bdf8', help_text='Warna angka kartu dan garis chart, mis. #38bdf8.', max_length=7, verbose_name='Warna')),
                ('aktif', models.BooleanField(default=False, help_text='Hilangkan centang untuk menyembunyikan kartu dan chart-nya tanpa menghapus daftar anggotanya.', verbose_name='Tampilkan di Dashboard')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah Pada')),
                ('anggota', models.ManyToManyField(blank=True, help_text='Pilih satu atau beberapa. Totalnya yang tampil di kartu dan chart. Pembangkit yang tidak aktif tidak ikut terhitung.', related_name='pantauan_kit', to='opsis.pembangkit', verbose_name='Pembangkit yang Dipantau')),
            ],
            options={
                'verbose_name': 'Pantauan KIT Terpilih',
                'verbose_name_plural': 'Pantauan KIT Terpilih',
            },
        ),
    ]
