# Generated by Django 6.0.2 on 2026-09-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0025_pantauankit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanInersia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=False, help_text='Hilangkan centang untuk menyembunyikan kartu dan chart-nya tanpa menghapus pengaturannya.', verbose_name='Tampilkan di Dashboard')),
                ('nama', models.CharField(default='Inersia Sistem', help_text='Tampil sebagai judul kartu kecil dan chart-nya di dashboard.', max_length=80, verbose_name='Judul Kartu')),
                ('rocof_batas', models.FloatField(default=1.0, help_text='Laju perubahan frekuensi yang masih dianggap aman, mis. 1 Hz/s. Dipakai menghitung dP = 2 x E x ROCOF / f0.', verbose_name='Batas ROCOF (Hz/s)')),
                ('frekuensi_nominal', models.FloatField(default=50.0, help_text='Umumnya 50 Hz.', verbose_name='Frekuensi Nominal f0 (Hz)')),
                ('hanya_beroperasi', models.BooleanField(default=True, help_text='Hanya mesin yang tersinkron menyimpan energi kinetik, jadi bawaannya dicentang — pembangkit dengan MW di bawah ambang di bawah ini tidak ikut dihitung. Hilangkan centang untuk memakai seluruh pembangkit yang punya MVA & H (angkanya jadi kapasitas inersia terpasang, dan grafiknya praktis datar).', verbose_name='Hitung Hanya Pembangkit yang Beroperasi')),
                ('ambang_mw', models.FloatField(default=1.0, help_text='Pembangkit dengan MW lebih besar dari angka ini dianggap tersinkron. Bukan nol supaya derau pengukuran kecil tidak terbaca sebagai mesin yang berputar.', verbose_name='Ambang MW Dianggap Beroperasi')),
                ('warna', models.CharField(default='#22d3ee', help_text='Warna angka E dan garis chart-nya, mis. #22d3ee.', max_length=7, verbose_name='Warna Energi Kinetik')),
                ('warna_delta', models.CharField(default='#fb923c', help_text='Warna angka dP dan garis chart-nya.', max_length=7, verbose_name='Warna dP')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah Pada')),
            ],
            options={
                'verbose_name': 'Pengaturan Inersia Sistem',
                'verbose_name_plural': 'Pengaturan Inersia Sistem',
            },
        ),
        migrations.AddField(
            model_name='pembangkit',
            name='inersia_h',
            field=models.FloatField(blank=True, help_text='Konstanta inersia mesin dalam detik, umumnya 2-9 s. Energi kinetiknya = MVA x H (MWs).', null=True, verbose_name='Konstanta Inersia H (detik)'),
        ),
        migrations.AddField(
            model_name='pembangkit',
            name='mva',
            field=models.FloatField(blank=True, help_text='Daya semu terpasang dalam MVA. Kosongkan bila pembangkit ini tidak diikutkan hitungan inersia.', null=True, verbose_name='Kapasitas S (MVA)'),
        ),
    ]
