# Generated by Django 6.0.2 on 2026-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0026_pengaturaninersia_pembangkit_inersia_h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tampil_trafo_distribusi', models.BooleanField(default=True, help_text='Kartu ringkasan dan chart "Beban Trafo Distribusi — per GI" di dashboard. Dimatikan = keduanya hilang dan polling-nya berhenti.', verbose_name='Tampilkan Beban Trafo Distribusi')),
                ('tampil_trafo_ibt', models.BooleanField(default=True, help_text='Kartu ringkasan dan chart "Beban Trafo IBT — per Trafo" di dashboard. Dimatikan = keduanya hilang dan polling-nya berhenti.', verbose_name='Tampilkan Beban Trafo IBT')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah Pada')),
            ],
            options={
                'verbose_name': 'Pengaturan Tampilan Dashboard',
                'verbose_name_plural': 'Pengaturan Tampilan Dashboard',
            },
        ),
    ]
