# Generated by Django 6.0.2 on 2026-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsis', '0027_pengaturandashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapKtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog', models.CharField(db_index=True, max_length=50, verbose_name='Kode ANALOG')),
                ('waktu', models.DateTimeField()),
                ('mw', models.FloatField(null=True, verbose_name='Beban (MW)')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot Beban KTT',
                'verbose_name_plural': 'Snapshot Beban KTT',
                'ordering': ['-waktu'],
                'indexes': [models.Index(fields=['analog', '-waktu'], name='opsis_snapk_analog_018f74_idx')],
                'unique_together': {('analog', 'waktu')},
            },
        ),
    ]
