# Generated by Django 6.0.2 on 2026-09-09 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0028_snapktt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SumberKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            (
                                "kolom",
                                "Kolom — satu baris per KIT, kolomnya UNIT1_P/UNIT1_Q ... (bentuk KIT_REALTIME)",
                            ),
                            (
                                "baris",
                                "Baris — satu titik per baris (kolom kunci + kolom nilai, bentuk ALL_TRANS_DATA)",
                            ),
                        ],
                        default="kolom",
                        max_length=10,
                        verbose_name="Bentuk Tabel Sumber",
                    ),
                ),
                (
                    "tabel",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kosongkan untuk memakai MSSQL_RT_TABLE dari .env (bawaan: dbo.KIT_REALTIME). Contoh: dbo.KIT_REALTIME_BARU",
                        max_length=100,
                        verbose_name="Tabel Sumber (MSSQL)",
                    ),
                ),
                (
                    "kolom_kunci",
                    models.CharField(
                        blank=True,
                        default="KIT",
                        help_text="Mode Kolom: kolom berisi kode KIT, dicocokkan dengan Kode KIT pembangkit. Mode Baris: kolom penanda titik, mis. ANALOG.",
                        max_length=50,
                        verbose_name="Kolom Kunci",
                    ),
                ),
                (
                    "kolom_waktu",
                    models.CharField(
                        blank=True,
                        default="DATE",
                        help_text='Kolom stempel waktu baris. Kosongkan bila tabelnya tidak punya — kartu tetap jalan, hanya jam "update" yang tidak terisi.',
                        max_length=50,
                        verbose_name="Kolom Waktu",
                    ),
                ),
                (
                    "jumlah_unit",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Berapa pasang kolom unit yang dibaca (UNIT1..UNITn). KIT_REALTIME: 8.",
                        verbose_name="Jumlah Unit per Baris",
                    ),
                ),
                (
                    "pola_kolom_p",
                    models.CharField(
                        blank=True,
                        default="UNIT{n}_P",
                        help_text="{n} diganti nomor unit. Contoh: UNIT{n}_P menghasilkan UNIT1_P, UNIT2_P, ...",
                        max_length=50,
                        verbose_name="Pola Kolom P (MW)",
                    ),
                ),
                (
                    "pola_kolom_q",
                    models.CharField(
                        blank=True,
                        default="UNIT{n}_Q",
                        help_text="Kosongkan bila tabel sumber tidak menyimpan MVAR — kartu MVAR akan kosong, MW tetap jalan.",
                        max_length=50,
                        verbose_name="Pola Kolom Q (MVAR)",
                    ),
                ),
                (
                    "kolom_nilai",
                    models.CharField(
                        blank=True,
                        default="VALUE",
                        help_text="Hanya mode Baris — kolom berisi angkanya. Umumnya VALUE.",
                        max_length=50,
                        verbose_name="Kolom Nilai",
                    ),
                ),
                (
                    "diubah_pada",
                    models.DateTimeField(auto_now=True, verbose_name="Diubah Pada"),
                ),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diubah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sumber Data KIT (Live)",
                "verbose_name_plural": "Sumber Data KIT (Live)",
            },
        ),
        migrations.CreateModel(
            name="TagUnitKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        default="UNIT1",
                        help_text="UNIT1, UNIT2, ... — nama yang tampil di kartu unit.",
                        max_length=20,
                        verbose_name="Nama Unit",
                    ),
                ),
                (
                    "tag_p",
                    models.CharField(
                        help_text="Nilai pada Kolom Kunci untuk daya aktif unit ini.",
                        max_length=100,
                        verbose_name="Tag P (MW)",
                    ),
                ),
                (
                    "tag_q",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Kosongkan bila MVAR unit ini tidak tersedia.",
                        max_length=100,
                        verbose_name="Tag Q (MVAR)",
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                (
                    "pembangkit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_unit",
                        to="opsis.pembangkit",
                        verbose_name="Pembangkit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Unit KIT (mode Baris)",
                "verbose_name_plural": "Tag Unit KIT (mode Baris)",
                "ordering": ["pembangkit", "urutan", "nama"],
                "unique_together": {("pembangkit", "nama")},
            },
        ),
    ]
