# Generated by Django 6.0.2 on 2026-09-09 06:47

import django.db.models.deletion
from django.db import migrations, models


def tandai_sumber_utama(apps, schema_editor):
    """
    Baris pengaturan lama (sumber tunggal) menjadi sumber utama, yaitu yang
    dipakai semua pembangkit yang belum menunjuk sumber sendiri. Tanpa ini
    tidak ada satu pun baris ber-utama=True setelah migrasi, dan pembangkit
    lama kehilangan angkanya sampai ada yang mencentangnya dari admin.
    """
    SumberKit = apps.get_model('opsis', 'SumberKit')
    if SumberKit.objects.filter(utama=True).exists():
        return
    lama = SumberKit.objects.order_by('pk').first()
    if lama is not None:
        lama.utama = True
        if not (lama.nama or '').strip():
            lama.nama = 'Bawaan (KIT_REALTIME)'
        lama.save(update_fields=['utama', 'nama'])


def batalkan(apps, schema_editor):
    """Tidak ada yang perlu dikembalikan — kolomnya sendiri dihapus RemoveField."""


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0029_sumberkit_tagunitkit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sumberkit",
            options={
                "ordering": ["-utama", "nama"],
                "verbose_name": "Sumber Data KIT (Live)",
                "verbose_name_plural": "Sumber Data KIT (Live)",
            },
        ),
        migrations.AddField(
            model_name="pembangkit",
            name="sumber",
            field=models.ForeignKey(
                blank=True,
                help_text="Kosongkan untuk mengikuti Sumber Utama. Isi hanya bila pembangkit ini dibaca dari tabel lain.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pembangkit",
                to="opsis.sumberkit",
                verbose_name="Sumber Data KIT",
            ),
        ),
        migrations.AddField(
            model_name="sumberkit",
            name="nama",
            field=models.CharField(
                default="Bawaan (KIT_REALTIME)",
                help_text='Nama untuk dikenali saat memilih sumber di tiap pembangkit, mis. "KIT_REALTIME lama" / "Historian baru".',
                max_length=80,
                unique=True,
                verbose_name="Nama Sumber",
            ),
        ),
        migrations.AddField(
            model_name="sumberkit",
            name="utama",
            field=models.BooleanField(
                default=False,
                help_text="Dipakai semua pembangkit yang tidak menunjuk sumber lain. Selalu ada tepat satu — mencentang di sini otomatis melepasnya dari sumber yang sebelumnya utama.",
                verbose_name="Sumber Utama",
            ),
        ),
        migrations.RunPython(tandai_sumber_utama, batalkan),
    ]
