# Generated by Django 6.0.2 on 2026-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opsis", "0030_alter_sumberkit_options_pembangkit_sumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengaturaninersia",
            name="keterangan_delta",
            field=models.CharField(
                blank=True,
                default="Daya maksimum yang boleh lepas mendadak sebelum ROCOF melewati batas rencana di atas.",
                help_text='Satu kalimat di bawah angka dP yang menjelaskan artinya. Teks ini juga dipakai sebagai baris "Arti dP" di sheet Ringkasan ekspor Excel, supaya layar dan berkas tidak bisa menyebut hal berbeda. Kosongkan untuk menyembunyikannya.',
                max_length=200,
                verbose_name="Keterangan dP",
            ),
        ),
        migrations.AddField(
            model_name="pengaturaninersia",
            name="label_delta",
            field=models.CharField(
                blank=True,
                default="Batas Aman Lepas Pembangkit",
                help_text="Nama pendek yang tampil di sebelah simbol ΔP di kartu. Kosongkan bila cukup simbolnya saja.",
                max_length=80,
                verbose_name="Label dP",
            ),
        ),
    ]
