# Generated by Django 6.0.2 on 2026-07-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KinerjaAnalogHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField(db_index=True)),
                ('path1', models.CharField(blank=True, default='', max_length=100)),
                ('path2', models.CharField(blank=True, default='', max_length=100)),
                ('path3', models.CharField(blank=True, default='', max_length=100)),
                ('tanggal', models.DateField(db_index=True)),
                ('jumlah_up', models.IntegerField(default=0)),
                ('uptime_detik', models.FloatField(default=0)),
                ('alltime_detik', models.FloatField(default=0)),
                ('performance', models.FloatField(default=0)),
                ('dihitung_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kinerja Analog Harian',
                'verbose_name_plural': 'Kinerja Analog Harian',
                'indexes': [models.Index(fields=['tanggal', 'point_number'], name='up2bmakassa_tanggal_3b21f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('point_number', 'tanggal'), name='uniq_kinerja_analog_harian')],
            },
        ),
        migrations.CreateModel(
            name='KinerjaDigitalHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField(db_index=True)),
                ('path1', models.CharField(blank=True, default='', max_length=100)),
                ('path2', models.CharField(blank=True, default='', max_length=100)),
                ('path3', models.CharField(blank=True, default='', max_length=100)),
                ('tanggal', models.DateField(db_index=True)),
                ('jumlah_up', models.IntegerField(default=0)),
                ('uptime_detik', models.FloatField(default=0)),
                ('alltime_detik', models.FloatField(default=0)),
                ('performance', models.FloatField(default=0)),
                ('dihitung_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kinerja Digital Harian',
                'verbose_name_plural': 'Kinerja Digital Harian',
                'indexes': [models.Index(fields=['tanggal', 'point_number'], name='up2bmakassa_tanggal_786b4a_idx')],
                'constraints': [models.UniqueConstraint(fields=('point_number', 'tanggal'), name='uniq_kinerja_digital_harian')],
            },
        ),
    ]
