# Generated by Django 6.0.2 on 2026-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up2bmakassar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePath1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path1', models.CharField(db_index=True, max_length=100, unique=True)),
                ('aktif', models.BooleanField(default=True, help_text='Kalau dicentang, semua titik dengan PATH1 ini ikut dihitung kinerjanya.')),
                ('keterangan', models.CharField(blank=True, default='', max_length=200)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site (PATH1) Aktif/Tidak',
                'verbose_name_plural': 'Site (PATH1) Aktif/Tidak',
                'ordering': ['path1'],
            },
        ),
    ]
