# Generated by Django 6.0.2 on 2026-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up2bmakassar', '0002_sitepath1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofdb_id_his_rc', models.IntegerField(db_index=True, unique=True)),
                ('path1', models.CharField(blank=True, default='', max_length=100)),
                ('path2', models.CharField(blank=True, default='', max_length=100)),
                ('path3', models.CharField(blank=True, default='', max_length=100)),
                ('path4', models.CharField(blank=True, default='', max_length=100)),
                ('path5', models.CharField(blank=True, default='', max_length=100)),
                ('b1', models.CharField(blank=True, default='', max_length=100)),
                ('b2', models.CharField(blank=True, default='', max_length=100)),
                ('b3', models.CharField(blank=True, default='', max_length=100)),
                ('elem', models.CharField(blank=True, default='', max_length=100)),
                ('operator', models.CharField(blank=True, default='', max_length=100)),
                ('tanggal', models.DateField(db_index=True)),
                ('datum_eksekusi', models.DateTimeField(blank=True, null=True)),
                ('status_eksekusi', models.CharField(blank=True, default='', max_length=100)),
                ('datum_respon', models.DateTimeField(blank=True, null=True)),
                ('status_respon', models.CharField(blank=True, default='', max_length=100)),
                ('dihitung_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remote Control (RC) Log',
                'verbose_name_plural': 'Remote Control (RC) Log',
                'indexes': [models.Index(fields=['tanggal'], name='up2bmakassa_tanggal_acf5ff_idx'), models.Index(fields=['path1', 'path2', 'path3'], name='up2bmakassa_path1_10d996_idx')],
            },
        ),
    ]
