# Generated by Django 6.0.2 on 2026-07-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogsheetTitik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("kit", "Pembangkit (KIT)"),
                            ("transmisi", "Transmisi / Penghantar"),
                            ("busbar", "Busbar (Tegangan)"),
                            ("trafo", "Trafo / IBT"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "besaran",
                    models.CharField(
                        choices=[
                            ("mw", "Daya Aktif (MW)"),
                            ("mvar", "Daya Reaktif (MVAR)"),
                            ("amp", "Arus (A)"),
                            ("volt", "Tegangan (kV)"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text='Identitas unik titik+besaran, mis. "KLKSM5-1:mw".',
                        max_length=60,
                        verbose_name="Kunci Titik",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nama/Label"
                    ),
                ),
                (
                    "mssql_tabel",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Tabel MSSQL"
                    ),
                ),
                (
                    "mssql_kolom",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Kolom MSSQL"
                    ),
                ),
                (
                    "mssql_keykol",
                    models.CharField(
                        blank=True,
                        help_text="Nama kolom untuk klausa WHERE, mis. KIT / ID / LINE.",
                        max_length=80,
                        verbose_name="Kolom Kunci (WHERE)",
                    ),
                ),
                (
                    "mssql_key",
                    models.CharField(
                        blank=True,
                        help_text="Nilai yang dicari pada kolom kunci.",
                        max_length=80,
                        verbose_name="Nilai Kunci",
                    ),
                ),
                (
                    "faktor",
                    models.FloatField(
                        default=1.0,
                        help_text="Nilai MSSQL dikali faktor ini (skala/kalibrasi).",
                        verbose_name="Faktor Kali",
                    ),
                ),
                (
                    "sheet",
                    models.CharField(
                        blank=True,
                        help_text="Nama sheet di template, mis. KIT_MW.",
                        max_length=40,
                        verbose_name="Sheet Export",
                    ),
                ),
                (
                    "baris",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nomor baris (1-based) tempat 48 kolom waktu diisi.",
                        null=True,
                        verbose_name="Baris Export",
                    ),
                ),
                ("aktif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Logsheet — Titik",
                "verbose_name_plural": "Logsheet — Titik",
                "ordering": ["kategori", "sheet", "baris", "key"],
                "unique_together": {("key",)},
            },
        ),
        migrations.CreateModel(
            name="LogsheetNilai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(db_index=True)),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="0 = 00:30, 1 = 01:00, … 47 = 24:00.",
                        verbose_name="Slot 30-menit",
                    ),
                ),
                (
                    "waktu",
                    models.DateTimeField(help_text="Waktu pengambilan sebenarnya."),
                ),
                ("nilai", models.FloatField(null=True)),
                (
                    "titik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nilai",
                        to="logsheet.logsheettitik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logsheet — Nilai",
                "verbose_name_plural": "Logsheet — Nilai",
                "ordering": ["-tanggal", "titik", "slot"],
                "indexes": [
                    models.Index(
                        fields=["tanggal", "titik"],
                        name="logsheet_lo_tanggal_d0ddef_idx",
                    )
                ],
                "unique_together": {("titik", "tanggal", "slot")},
            },
        ),
    ]
