# Generated by Django 6.0.2 on 2026-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logsheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsheettitik",
            name="kol0",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Kolom (1-based) untuk slot 00:30; 48 kolom ke kanan. Umumnya 6 (F); blok MVAR TRAFO = 55.",
                verbose_name="Kolom Slot-0",
            ),
        ),
    ]
