# Generated by Django 6.0.2 on 2026-03-26 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifikasi', '0002_notifikasi_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Kosong = tampil untuk semua user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL, verbose_name='Ditujukan ke'),
        ),
    ]
