# Generated by Django 6.0.2 on 2026-06-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifikasi', '0003_alter_notifikasi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='tipe',
            field=models.CharField(choices=[('hi_rendah', 'Health Index Rendah'), ('hi_turun', 'HI Turun Drastis'), ('maintenance_overdue', 'Maintenance Overdue'), ('gangguan_lama', 'Gangguan Terlalu Lama'), ('maintenance_ttd', 'Maintenance Perlu TTD'), ('gangguan_selesai', 'Gangguan Selesai — Perlu Review'), ('gangguan_baru', 'Gangguan Baru Dibuat'), ('corrective_selesai', 'Corrective Selesai'), ('ba_ttd_engineer', 'BA — Permintaan TTD Engineer'), ('ba_ttd_am', 'BA — Menunggu TTD AM')], max_length=30),
        ),
    ]
