# Generated by Django 6.0.2 on 2026-02-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='image',
        ),
        migrations.AddField(
            model_name='icon',
            name='SID1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='SID2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='kondisi_operasional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='kontrak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='lokasi_layanan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='nama_layanan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
