# Generated by Django 6.0.2 on 2026-03-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_add_spesifikasi_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='spesifikasi',
        ),
    ]
