# Generated by Django 6.0.2 on 2026-03-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_remove_device_spesifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='spesifikasi',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
