# Generated by Django 6.0.2 on 2026-03-26 00:54

import devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_device_public_token'),
        ('gangguan', '0007_gangguan_pelaksana_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=devices.models.device_foto_upload),
        ),
        migrations.AlterField(
            model_name='device',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to=devices.models.device_foto2_upload, verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='public_token',
            field=models.CharField(blank=True, help_text='Token unik untuk halaman publik QR Code', max_length=40, null=True, unique=True, verbose_name='Token Publik QR'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='gangguan',
            field=models.ForeignKey(blank=True, help_text='Opsional — hubungkan ke tiket gangguan terkait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perubahan_fisik', to='gangguan.gangguan', verbose_name='Terkait Gangguan'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='komponen',
            field=models.CharField(blank=True, help_text='Contoh: PSU, Modul CPU, Battery Bank', max_length=150, verbose_name='Komponen'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer (Hanya Lihat)'), ('technician', 'Teknisi / Engineer'), ('asisten_manager', 'Asisten Manager Operasi')], default='technician', max_length=30, verbose_name='Peran'),
        ),
        migrations.CreateModel(
            name='DeviceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: CPU 1, Slot A, PSU 1', max_length=150, verbose_name='Nama Komponen')),
                ('tipe_komponen', models.CharField(choices=[('psu', 'Power Supply Unit'), ('fan', 'Fan / Cooling'), ('modul_generic', 'Modul (Umum)'), ('modul_cpu', 'Modul CPU'), ('modul_slot', 'Modul Slot (Card)'), ('modul_hs', 'Modul HS (High Speed)'), ('sfp', 'SFP / Transceiver'), ('port_lan', 'Port LAN'), ('port_uplink', 'Port Uplink'), ('modul_rectifier', 'Modul Rectifier'), ('battery', 'Battery Bank'), ('battery_cell', 'Battery Cell'), ('antena', 'Antena'), ('modul_radio', 'Modul Radio TX/RX'), ('modul_plc', 'Modul PLC'), ('wave_trap', 'Wave Trap'), ('imu', 'IMU / Coupling'), ('lainnya', 'Lainnya')], max_length=30, verbose_name='Tipe Komponen')),
                ('posisi', models.CharField(blank=True, help_text='Contoh: Slot A, Bay 1, Port 3', max_length=50, verbose_name='Posisi / Slot')),
                ('merk', models.CharField(blank=True, max_length=100, verbose_name='Merk')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model / Tipe')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('terpasang', 'Terpasang & Normal'), ('rusak', 'Rusak'), ('diganti', 'Sudah Diganti'), ('tidak_ada', 'Tidak Terpasang')], default='terpasang', max_length=20, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('tanggal_pasang', models.DateField(blank=True, null=True, verbose_name='Tanggal Pemasangan')),
                ('tanggal_ganti', models.DateField(blank=True, null=True, verbose_name='Tanggal Penggantian Terakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ditambahkan oleh')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponen', to='devices.device', verbose_name='Perangkat Induk')),
                ('parent', models.ForeignKey(blank=True, help_text='Kosongkan jika ini komponen level atas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_komponen', to='devices.devicecomponent', verbose_name='Komponen Induk')),
            ],
            options={
                'verbose_name': 'Komponen Perangkat',
                'verbose_name_plural': 'Komponen Perangkat',
                'ordering': ['device', 'posisi', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='SpecBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_baterai', models.CharField(blank=True, choices=[('vrla', 'VRLA / AGM'), ('gel', 'Gel'), ('lithium', 'Lithium-Ion'), ('wet', 'Wet Cell')], max_length=20)),
                ('kapasitas_ah', models.FloatField(blank=True, null=True, verbose_name='Kapasitas (Ah)')),
                ('tegangan_nominal', models.FloatField(blank=True, null=True, verbose_name='Tegangan Nominal (V)')),
                ('jumlah_cell', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Cell')),
                ('tanggal_pasang_baterai', models.DateField(blank=True, null=True, verbose_name='Tgl Pasang Baterai')),
                ('umur_desain_tahun', models.IntegerField(blank=True, null=True, verbose_name='Umur Desain (tahun)')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_battery', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec Battery',
            },
        ),
        migrations.CreateModel(
            name='SpecBatteryCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_cell', models.IntegerField(verbose_name='Nomor Cell')),
                ('tegangan_float', models.FloatField(blank=True, null=True, verbose_name='V Float')),
                ('tegangan_boost', models.FloatField(blank=True, null=True, verbose_name='V Boost')),
                ('internal_resistance', models.FloatField(blank=True, null=True, verbose_name='Internal Resistance (mOhm)')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_battery_cell', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec Battery Cell',
                'ordering': ['nomor_cell'],
            },
        ),
        migrations.CreateModel(
            name='SpecMuxSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_modul', models.CharField(choices=[('-', 'Kosong'), ('E1Q', 'E1Q'), ('16E1Q', '16E1Q'), ('V.35', 'V.35'), ('6V.35', '6V.35'), ('SWITCH', 'SWITCH'), ('G.64', 'G.64'), ('E&M', 'E&M'), ('HDSL', 'HDSL')], default='-', max_length=20, verbose_name='Tipe Modul')),
                ('firmware', models.CharField(blank=True, max_length=50, verbose_name='Firmware Version')),
                ('isian', models.TextField(blank=True, verbose_name='Isian / Konfigurasi')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_mux_slot', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec Slot Multiplexer',
            },
        ),
        migrations.CreateModel(
            name='SpecPLCModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_tx', models.FloatField(blank=True, null=True, verbose_name='Frekuensi TX (kHz)')),
                ('bandwidth_tx', models.FloatField(blank=True, null=True, verbose_name='Bandwidth TX (kHz)')),
                ('freq_rx', models.FloatField(blank=True, null=True, verbose_name='Frekuensi RX (kHz)')),
                ('bandwidth_rx', models.FloatField(blank=True, null=True, verbose_name='Bandwidth RX (kHz)')),
                ('tx_level', models.FloatField(blank=True, null=True, verbose_name='TX Level (dBm)')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_plc_modul', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec PLC Modul',
            },
        ),
        migrations.CreateModel(
            name='SpecPSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegangan_input', models.CharField(blank=True, max_length=30, verbose_name='Tegangan Input')),
                ('tegangan_output', models.CharField(blank=True, max_length=30, verbose_name='Tegangan Output')),
                ('kapasitas_watt', models.FloatField(blank=True, null=True, verbose_name='Kapasitas (Watt)')),
                ('redundan', models.BooleanField(default=False, verbose_name='Redundan?')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_psu', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec PSU',
            },
        ),
        migrations.CreateModel(
            name='SpecRadioModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frekuensi_tx', models.CharField(blank=True, max_length=30, verbose_name='Frekuensi TX')),
                ('frekuensi_rx', models.CharField(blank=True, max_length=30, verbose_name='Frekuensi RX')),
                ('tx_power_watt', models.FloatField(blank=True, null=True, verbose_name='TX Power (W)')),
                ('tipe_modulasi', models.CharField(blank=True, max_length=30, verbose_name='Tipe Modulasi')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_radio_modul', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec Radio Modul',
            },
        ),
        migrations.CreateModel(
            name='SpecRectifierModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapasitas_ampere', models.FloatField(blank=True, null=True, verbose_name='Kapasitas (A)')),
                ('tegangan_output', models.CharField(blank=True, max_length=30, verbose_name='Tegangan Output')),
                ('efisiensi', models.FloatField(blank=True, null=True, verbose_name='Efisiensi (%)')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_rectifier_modul', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec Modul Rectifier',
            },
        ),
        migrations.CreateModel(
            name='SpecRouterPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecepatan', models.CharField(blank=True, choices=[('100M', '100 Mbps'), ('1G', '1 Gbps'), ('10G', '10 Gbps'), ('25G', '25 Gbps'), ('40G', '40 Gbps')], max_length=10, verbose_name='Kecepatan')),
                ('wavelength', models.CharField(blank=True, max_length=30, verbose_name='Wavelength (nm)')),
                ('tx_power', models.FloatField(blank=True, null=True, verbose_name='TX Power (dBm)')),
                ('rx_power', models.FloatField(blank=True, null=True, verbose_name='RX Power (dBm)')),
                ('jarak_max', models.CharField(blank=True, max_length=30, verbose_name='Jarak Max')),
                ('tipe_konektor', models.CharField(blank=True, max_length=30, verbose_name='Tipe Konektor')),
                ('komponen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_sfp', to='devices.devicecomponent')),
            ],
            options={
                'verbose_name': 'Spec SFP / Port',
            },
        ),
    ]
