# Generated by Django 6.0.2 on 2026-03-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_device_foto_alter_device_foto2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupTipeKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama Grup')),
                ('urutan', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan Tampil')),
            ],
            options={
                'verbose_name': 'Grup Tipe Komponen',
                'verbose_name_plural': 'Grup Tipe Komponen',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TipeKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode pendek unik, e.g. psu, sfp, modul_cpu', max_length=30, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Tipe')),
                ('urutan', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipe_komponen', to='devices.gruptipekomponen', verbose_name='Grup')),
            ],
            options={
                'verbose_name': 'Tipe Komponen',
                'verbose_name_plural': 'Tipe Komponen',
                'ordering': ['grup__urutan', 'urutan', 'nama'],
            },
        ),
        migrations.AlterField(
            model_name='devicecomponent',
            name='tipe_komponen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komponen', to='devices.tipekomponen', verbose_name='Tipe Komponen'),
        ),
    ]
