# Generated by Django 6.0.2 on 2026-03-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_device_foto_alter_device_foto2_and_more'),
        ('devices', '0021_tipe_komponen_to_db'),
    ]

    operations = [
    ]
