# Generated by Django 6.0.2 on 2026-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_userprofile_active_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberoptic',
            name='tipe_kabel',
            field=models.CharField(blank=True, choices=[('ADSS', 'ADSS (All-Dielectric Self-Supporting)'), ('OPGW', 'OPGW (Optical Ground Wire)'), ('DROP', 'Drop Cable')], max_length=20, null=True, verbose_name='Tipe Kabel'),
        ),
        migrations.AlterField(
            model_name='fiberoptic',
            name='tipe_konektor',
            field=models.CharField(blank=True, choices=[('SC', 'SC (subscriber Connector)'), ('LC', 'LC (Lucent Connector)'), ('FC', 'FC (Ferrule Connector)'), ('lainnya', 'Lainnya')], max_length=20, null=True, verbose_name='Tipe Konektor'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_catatan',
            field=models.TextField(blank=True, help_text='Temuan, anomali, atau catatan hasil pengukuran', null=True, verbose_name='Catatan OTDR'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_jarak_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Jarak total atau jarak ke titik gangguan', max_digits=8, null=True, verbose_name='OTDR Jarak (km)'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_redaman_db',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total redaman kabel', max_digits=6, null=True, verbose_name='OTDR Redaman (dB)'),
        ),
    ]
