# Generated by Django 6.0.2 on 2026-04-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_device_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultg',
            name='lokasi',
            field=models.ManyToManyField(blank=True, help_text='Pilih semua Gardu Induk yang berada di bawah ULTG ini', to='devices.sitelocation', verbose_name='Lokasi / GI yang dibawahi'),
        ),
        migrations.AlterField(
            model_name='ultg',
            name='nama',
            field=models.CharField(help_text='Contoh: ULTG Makassar, ULTG Pare-Pare', max_length=100, unique=True, verbose_name='Nama ULTG'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ultg',
            field=models.ForeignKey(blank=True, help_text='Untuk role Operator — ULTG yang dilayani. Inspeksi hanya menampilkan lokasi ULTG ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='devices.ultg', verbose_name='ULTG'),
        ),
    ]
