# Generated by Django 6.0.2 on 2026-04-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_alter_ultg_lokasi_alter_ultg_nama_and_more'),
        ('devices', '0033_fiberoptic_konektor_ab_foto'),
    ]

    operations = [
    ]
