# Generated by Django 6.0.2 on 2026-04-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0034_fiberoptic_konfigurasi_fiberopticcore_koneksi'),
        ('devices', '0034_merge_20260413_1207'),
    ]

    operations = [
    ]
