# Generated by Django 6.0.2 on 2026-04-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_fiberopticcore_otdr_b'),
        ('devices', '0035_merge_20260415_1103'),
    ]

    operations = [
    ]
