# Generated by Django 6.0.2 on 2026-04-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_fiberopticcore_status_ab'),
        ('devices', '0036_merge_20260415_1114'),
    ]

    operations = [
    ]
