# Generated by Django 6.0.2 on 2026-04-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_merge_20260415_1419'),
        ('devices', '0038_device_wiring'),
    ]

    operations = [
    ]
