# Generated by Django 6.0.2 on 2026-04-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_merge_0037_merge_20260415_1419_0038_device_wiring'),
        ('devices', '0040_fiberopticcore_lambda_fields'),
    ]

    operations = [
    ]
