# Generated by Django 6.0.2 on 2026-04-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_core_per_site_lambda_jarak'),
        ('devices', '0041_merge_20260420_2223'),
    ]

    operations = [
    ]
