# Generated by Django 6.0.2 on 2026-04-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0042_fiberopticcore_fungsi_b_keterangan_b'),
        ('devices', '0042_merge_20260422_0856'),
    ]

    operations = [
    ]
