# Generated by Django 6.0.2 on 2026-05-04 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0044_alter_fiberopticcore_otdr_b_catatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='merk_komponen_baru',
            field=models.CharField(blank=True, help_text='Merk komponen pengganti (isi saat penggantian)', max_length=100, verbose_name='Merk Komponen Baru'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='tipe_komponen_baru',
            field=models.CharField(blank=True, help_text='Tipe atau model komponen pengganti', max_length=100, verbose_name='Tipe / Model Komponen Baru'),
        ),
        migrations.CreateModel(
            name='KomponenRusak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komponen', models.CharField(max_length=150, verbose_name='Nama Komponen')),
                ('merk', models.CharField(blank=True, max_length=100, verbose_name='Merk')),
                ('tipe', models.CharField(blank=True, max_length=100, verbose_name='Tipe / Model')),
                ('tanggal_rusak', models.DateField(verbose_name='Tanggal Diganti / Rusak')),
                ('disimpan_di', models.CharField(blank=True, help_text='Lokasi penyimpanan komponen rusak, misal: Gudang Teknik, Loker B2', max_length=200, verbose_name='Disimpan Di')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komponen_rusak_dicatat', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat oleh')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponen_rusak', to='devices.device', verbose_name='Perangkat')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komponen_rusak_set', to='devices.deviceevent', verbose_name='Sumber Kejadian')),
                ('komponen_terkait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_rusak', to='devices.devicecomponent', verbose_name='Referensi Komponen')),
            ],
            options={
                'verbose_name': 'Komponen Rusak',
                'verbose_name_plural': 'Daftar Komponen Rusak',
                'ordering': ['-tanggal_rusak', '-created_at'],
            },
        ),
    ]
