# Generated by Django 6.0.2 on 2026-05-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_merge_20260422_0922'),
        ('devices', '0045_add_komponen_baru_fields_and_komponen_rusak'),
    ]

    operations = [
    ]
