# Generated by Django 6.0.2 on 2026-05-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0044_alter_fiberopticcore_otdr_b_catatan_and_more'),
        ('devices', '0045_add_komponen_baru_fields_and_komponen_rusak'),
    ]

    operations = [
    ]
