# Generated by Django 6.0.2 on 2026-05-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0046_devicelink'),
        ('devices', '0046_merge_20260504_0938'),
    ]

    operations = [
    ]
