# Generated by Django 6.0.2 on 2026-05-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0047_merge_0046_devicelink_0046_merge_20260504_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_b_catatan',
            field=models.TextField(blank=True, null=True, verbose_name='OTDR B Catatan'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_catatan',
            field=models.TextField(blank=True, null=True, verbose_name='OTDR A Catatan'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_tanggal',
            field=models.DateField(blank=True, null=True, verbose_name='OTDR A Tanggal Pengukuran'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif / Digunakan'), ('spare', 'Spare / Cadangan'), ('rusak', 'Rusak / Putus'), ('tidak_aktif', 'Tidak Aktif')], default='spare', max_length=20, verbose_name='Status Core (overall)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer (Hanya Lihat)'), ('operator', 'Operator'), ('technician', 'Teknisi / Engineer'), ('asisten_manager', 'Asisten Manager Operasi'), ('opsis', 'Opsis — Monitoring Pembangkit')], default='technician', max_length=30, verbose_name='Peran'),
        ),
    ]
