# Generated by Django 6.0.2 on 2026-05-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0047_ip_unique_per_lokasi'),
        ('devices', '0048_alter_devicelink_id_and_more'),
    ]

    operations = [
    ]
