# Generated by Django 6.0.2 on 2026-05-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0049_komponenrusak_branch'),
        ('devices', '0050_merge_0048_branch_0049_merge_20260509_2201'),
    ]

    operations = [
    ]
