# Generated by Django 6.0.2 on 2026-06-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0051_merge_20260513_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
