# Generated by Django 6.0.2 on 2026-06-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_alter_branch_id'),
        ('devices', '0052_userprofile_branch'),
    ]

    operations = [
    ]
