# Generated by Django 6.0.2 on 2026-06-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0053_merge_0052_alter_branch_id_0052_userprofile_branch'),
        ('devices', '0054_deviceevent_penggantian_perangkat'),
    ]

    operations = [
    ]
