# Generated by Django 6.0.2 on 2026-07-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0055_alasan_penggantian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='alasan_penggantian',
            field=models.CharField(blank=True, choices=[('rusak', 'Rusak / Tidak Berfungsi'), ('kinerja', 'Kinerja Menurun'), ('improvement', 'Improvement / Upgrade Kehandalan'), ('lifetime', 'Habis Masa Pakai'), ('preventif', 'Pemeliharaan Preventif'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Penggantian / Pembongkaran'),
        ),
        migrations.AlterField(
            model_name='devicelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_catatan',
            field=models.TextField(blank=True, null=True, verbose_name='OTDR A Catatan'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='otdr_tanggal',
            field=models.DateField(blank=True, null=True, verbose_name='OTDR A Tanggal Pengukuran'),
        ),
        migrations.AlterField(
            model_name='fiberopticcore',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif / Digunakan'), ('spare', 'Spare / Cadangan'), ('rusak', 'Rusak / Putus'), ('tidak_aktif', 'Tidak Aktif')], default='spare', max_length=20, verbose_name='Status Core (overall)'),
        ),
        migrations.AlterField(
            model_name='itembongkar',
            name='alasan_penggantian',
            field=models.CharField(blank=True, choices=[('rusak', 'Rusak / Tidak Berfungsi'), ('kinerja', 'Kinerja Menurun'), ('improvement', 'Improvement / Upgrade Kehandalan'), ('lifetime', 'Habis Masa Pakai'), ('preventif', 'Pemeliharaan Preventif'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Pembongkaran / Penggantian'),
        ),
        migrations.AlterField(
            model_name='itembongkar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='komponenrusak',
            name='alasan_penggantian',
            field=models.CharField(blank=True, choices=[('rusak', 'Rusak / Tidak Berfungsi'), ('kinerja', 'Kinerja Menurun'), ('improvement', 'Improvement / Upgrade Kehandalan'), ('lifetime', 'Habis Masa Pakai'), ('preventif', 'Pemeliharaan Preventif'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Penggantian'),
        ),
        migrations.AlterField(
            model_name='ultg',
            name='lokasi',
            field=models.ManyToManyField(blank=True, help_text='Pilih semua Gardu Induk yang berada di bawah ULTG ini', to='devices.sitelocation', verbose_name='Lokasi / GI yang dibawahi'),
        ),
        migrations.AlterField(
            model_name='ultg',
            name='nama',
            field=models.CharField(help_text='Contoh: ULTG Makassar, ULTG Pare-Pare', max_length=100, unique=True, verbose_name='Nama ULTG'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer (Hanya Lihat)'), ('operator', 'Operator'), ('dispatcher', 'Dispatcher — Pengujian Telekomunikasi'), ('technician', 'Teknisi / Engineer'), ('asisten_manager', 'Asisten Manager Operasi'), ('opsis', 'Opsis — Monitoring Pembangkit'), ('up2d', 'UP2D — Dashboard Beban Sistem')], default='technician', max_length=30, verbose_name='Peran'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ultg',
            field=models.ForeignKey(blank=True, help_text='Untuk role Operator — ULTG yang dilayani. Inspeksi hanya menampilkan lokasi ULTG ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='devices.ultg', verbose_name='ULTG'),
        ),
    ]
