# Generated by Django 6.0.2 on 2026-06-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0055_alasan_penggantian'),
        ('devices', '0055_merge_20260608_0946'),
    ]

    operations = [
    ]
