# Generated by Django 6.0.2 on 2026-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0056_merge_20260609_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='alasan_penggantian',
            field=models.CharField(blank=True, choices=[('rusak', 'Rusak / Tidak Berfungsi'), ('kinerja', 'Kinerja Menurun'), ('improvement', 'Improvement / Upgrade Kehandalan'), ('lifetime', 'Habis Masa Pakai'), ('preventif', 'Pemeliharaan Preventif'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Penggantian / Pembongkaran'),
        ),
        migrations.AlterField(
            model_name='itembongkar',
            name='alasan_penggantian',
            field=models.CharField(blank=True, choices=[('rusak', 'Rusak / Tidak Berfungsi'), ('kinerja', 'Kinerja Menurun'), ('improvement', 'Improvement / Upgrade Kehandalan'), ('lifetime', 'Habis Masa Pakai'), ('preventif', 'Pemeliharaan Preventif'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Pembongkaran / Penggantian'),
        ),
        migrations.AlterField(
            model_name='itembongkar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='komponenrusak',
            name='alasan_penggantian',
            field=models.CharField(blank=True, choices=[('rusak', 'Rusak / Tidak Berfungsi'), ('kinerja', 'Kinerja Menurun'), ('improvement', 'Improvement / Upgrade Kehandalan'), ('lifetime', 'Habis Masa Pakai'), ('preventif', 'Pemeliharaan Preventif'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Alasan Penggantian'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer (Hanya Lihat)'), ('operator', 'Operator'), ('dispatcher', 'Dispatcher — Pengujian Telekomunikasi'), ('technician', 'Teknisi / Engineer'), ('asisten_manager', 'Asisten Manager Operasi'), ('opsis', 'Opsis — Monitoring Pembangkit'), ('up2d', 'UP2D — Dashboard Beban Sistem')], default='technician', max_length=30, verbose_name='Peran'),
        ),
    ]
