# Generated by Django 6.0.2 on 2026-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0057_alter_deviceevent_alasan_penggantian_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bisa_input_hop",
            field=models.BooleanField(
                default=False,
                help_text="Jika aktif, user (khususnya role Opsis) boleh menginput nilai HOP pembangkit harian. Tidak semua user Opsis diberi izin ini.",
                verbose_name="Boleh Input Data HOP",
            ),
        ),
    ]
