# Generated by Django 6.0.2 on 2026-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0058_userprofile_bisa_input_hop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bisa_input_hop",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer (Hanya Lihat)"),
                    ("operator", "Operator"),
                    ("dispatcher", "Dispatcher — Pengujian Telekomunikasi"),
                    ("technician", "Teknisi / Engineer"),
                    ("asisten_manager", "Asisten Manager Operasi"),
                    (
                        "opsis",
                        "Opsis — Monitoring Pembangkit (Input Data, Sesi Tunggal)",
                    ),
                    ("opsis_view", "Opsis View — Monitoring (Lihat Saja, Multi-Sesi)"),
                    ("up2d", "UP2D — Dashboard Beban Sistem"),
                ],
                default="technician",
                max_length=30,
                verbose_name="Peran",
            ),
        ),
    ]
