# Generated by Django 6.0.2 on 2026-08-05 13:32

import devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0059_remove_userprofile_bisa_input_hop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=devices.models.foto_lapangan_upload)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=devices.models.foto_lapangan_thumb_upload)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Ambil (EXIF)')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unassigned', 'Belum Diarahkan'), ('assigned', 'Sudah Diarahkan')], default='unassigned', max_length=12)),
                ('assigned_as', models.CharField(blank=True, choices=[('foto', 'Foto Device 1'), ('foto2', 'Foto Device 2'), ('eviden', 'Eviden Tambahan')], default='', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foto_lapangan_assigned', to='devices.device')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto Lapangan',
                'verbose_name_plural': 'Foto Lapangan',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
