# Generated by Django 6.0.2 on 2026-08-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0060_fotolapangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotolapangan',
            name='folder',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Label pengelompokan bebas (mis. nama GI/lokasi). Kosong = Tanpa Folder.', max_length=150, verbose_name='Folder / Lokasi'),
        ),
    ]
