# Generated by Django 6.0.2 on 2026-08-07 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0060_fotolapangan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_deleted', 'jenis'], name='device_del_jenis_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_deleted', 'lokasi'], name='device_del_lokasi_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_deleted', 'host'], name='device_del_host_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_deleted', 'status_operasi'], name='device_del_status_idx'),
        ),
    ]
