# Generated by Django 6.0.2 on 2026-08-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0061_fotolapangan_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status_aset',
            field=models.CharField(choices=[('UP2B', 'UP2B'), ('IPP', 'IPP'), ('BELUM_STAP', 'Belum STAP')], db_index=True, default='UP2B', help_text='Kepemilikan aset. Hanya UP2B yang masuk perhitungan jumlah aset.', max_length=12, verbose_name='Status Aset'),
        ),
    ]
