# Generated by Django 6.0.2 on 2026-08-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0061_db_indexes'),
        ('devices', '0062_device_status_aset'),
    ]

    operations = [
    ]
