# Generated by Django 6.0.2 on 2026-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0063_merge_0061_db_indexes_0062_device_status_aset'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Nomor identitas aset (angka).', max_length=30, null=True, verbose_name='Asset ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status_aset',
            field=models.CharField(db_index=True, default='UP2B', help_text='Kepemilikan aset. Hanya UP2B yang masuk perhitungan jumlah aset.', max_length=50, verbose_name='Status Aset'),
        ),
    ]
