# Generated by Django 6.0.2 on 2026-09-07 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0064_add_asset_id_and_open_status_aset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KunciApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Siapa pemakai kunci ini, mis. "UP2D Sulselrabar — dashboard beban".', max_length=100, verbose_name='Nama Konsumen')),
                ('kunci', models.CharField(db_index=True, help_text='Dikirim konsumen di header X-API-Key. Dibuat otomatis bila dikosongkan.', max_length=64, unique=True, verbose_name='Kunci')),
                ('aktif', models.BooleanField(default=True, help_text='Hilangkan centang untuk mencabut akses seketika, tanpa menghapus riwayatnya.', verbose_name='Aktif')),
                ('keterangan', models.TextField(blank=True, default='', help_text='Kontak PIC, nomor surat permintaan data, dsb.', verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('terakhir_dipakai', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Dipakai')),
                ('terakhir_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Terakhir')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunci_api_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Kunci API',
                'verbose_name_plural': 'Kunci API',
                'ordering': ['nama'],
            },
        ),
    ]
