# Generated by Django 6.0.2 on 2026-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0065_kunciapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunciapi',
            name='kunci',
            field=models.CharField(blank=True, db_index=True, help_text='Dikirim konsumen di header X-API-Key. Dibuat otomatis bila dikosongkan.', max_length=64, unique=True, verbose_name='Kunci'),
        ),
    ]
