# Generated by Django 6.0.2 on 2026-09-08 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0066_alter_kunciapi_kunci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer (Hanya Lihat)'), ('operator', 'Operator'), ('dispatcher', 'Dispatcher — Pengujian Telekomunikasi'), ('technician', 'Teknisi / Engineer'), ('asisten_manager', 'Asisten Manager Operasi'), ('opsis', 'Opsis — Monitoring Pembangkit (Input Data, Sesi Tunggal)'), ('opsis_view', 'Opsis View — Monitoring (Lihat Saja, Multi-Sesi)'), ('up2d', 'UP2D — Dashboard Beban Sistem'), ('vendor', 'Vendor — Asesmen Optik (Hanya Asesmen)')], default='technician', max_length=30, verbose_name='Peran'),
        ),
        migrations.CreateModel(
            name='AsesmenOptik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tower', models.CharField(help_text='Contoh: 12 atau #012', max_length=20, verbose_name='No. Tower')),
                ('upt', models.CharField(blank=True, choices=[('UPT MAKASSAR', 'UPT MAKASSAR'), ('UPT PALU', 'UPT PALU'), ('UPT MANADO', 'UPT MANADO')], max_length=30, verbose_name='UPT')),
                ('level_tegangan', models.CharField(blank=True, choices=[('70 kV', '70 kV'), ('150 kV', '150 kV'), ('275 kV', '275 kV')], max_length=10, verbose_name='Level Tegangan')),
                ('tipe_tower', models.CharField(blank=True, max_length=50, verbose_name='Tipe Tower')),
                ('jarak_span', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jarak Span (m)')),
                ('lintang', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Lintang')),
                ('bujur', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Bujur')),
                ('fasa_fo', models.CharField(blank=True, choices=[('atas', 'Atas (R)'), ('tengah', 'Tengah (S)'), ('bawah', 'Bawah (T)')], max_length=10, verbose_name='Fasa FO')),
                ('tipe_kabel', models.CharField(blank=True, choices=[('ADSS', 'ADSS'), ('OPGW', 'OPGW')], help_text='Kosongkan untuk mengikuti tipe kabel ruasnya.', max_length=10, verbose_name='ADSS / OPGW')),
                ('kondisi_fo', models.CharField(blank=True, choices=[('baik', 'Baik'), ('anomali', 'Anomali'), ('rusak', 'Rusak')], max_length=10, verbose_name='Kondisi FO')),
                ('tipe_asesoris', models.CharField(blank=True, choices=[('tension', 'Tension'), ('suspension', 'Suspension')], max_length=15, verbose_name='Tipe Aksesoris')),
                ('kondisi_asesoris', models.CharField(blank=True, choices=[('baik', 'Baik'), ('anomali', 'Anomali'), ('tanpa_fitmen', 'Tanpa Fitmen')], max_length=15, verbose_name='Kondisi Aksesoris')),
                ('ukuran_fitmen', models.CharField(blank=True, max_length=50, verbose_name='Ukuran Fitmen')),
                ('joint_box', models.CharField(blank=True, choices=[('ada', 'Ada'), ('tidak_ada', 'Tidak Ada')], max_length=10, verbose_name='Joint Box')),
                ('asset', models.CharField(blank=True, help_text='Pemilik aset, mis. UP2B', max_length=50, verbose_name='Asset')),
                ('area_rintangan', models.CharField(blank=True, help_text='Mis. Rumah, Sawah, Sungai, Hutan Rawa', max_length=100, verbose_name='Area Jalur Rintangan SUTT')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='asesmen_optik/', verbose_name='Foto Tower / Aksesoris')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='asesmen_optik/', verbose_name='Foto Tambahan')),
                ('tanggal', models.DateField(verbose_name='Tanggal Asesmen')),
                ('petugas', models.CharField(blank=True, help_text='Nama pelaksana di lapangan.', max_length=150, verbose_name='Petugas / Vendor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesmen_optik_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Diinput oleh')),
                ('fiber_optic', models.ForeignKey(help_text='GI awal/akhir & tipe kabel mengikuti data ruas ini.', on_delete=django.db.models.deletion.CASCADE, related_name='asesmen', to='devices.fiberoptic', verbose_name='Ruas Fiber Optic')),
            ],
            options={
                'verbose_name': 'Asesmen Optik',
                'verbose_name_plural': 'Asesmen Optik',
                'ordering': ['-tanggal', 'fiber_optic', 'no_tower'],
                'indexes': [models.Index(fields=['fiber_optic', 'no_tower'], name='asesmen_ruas_tower_idx'), models.Index(fields=['-tanggal'], name='asesmen_tanggal_idx')],
            },
        ),
    ]
