# Generated by Django 6.0.2 on 2026-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0067_alter_userprofile_role_asesmenoptik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesmenoptik',
            name='bujur',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Bujur'),
        ),
        migrations.AlterField(
            model_name='asesmenoptik',
            name='lintang',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Lintang'),
        ),
    ]
