# Generated by Django 6.0.2 on 2026-09-10 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0068_alter_asesmenoptik_bujur_alter_asesmenoptik_lintang"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PengumumanPemeliharaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=False,
                        help_text="Bila dicentang, pop-up ini muncul sekali untuk setiap pengguna yang login. Hilangkan centangnya untuk menghentikannya.",
                        verbose_name="Tampilkan Pengumuman",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        default="Rencana Pemeliharaan Server",
                        max_length=120,
                        verbose_name="Judul",
                    ),
                ),
                (
                    "pesan",
                    models.TextField(
                        default="Server FASOP akan direstart untuk pemeliharaan terjadwal. Simpan pekerjaan Anda terlebih dahulu — aplikasi tidak dapat diakses selama proses berlangsung.",
                        help_text="Isi pengumuman. Ditampilkan apa adanya (baris baru dipertahankan), tanpa HTML.",
                        verbose_name="Pesan",
                    ),
                ),
                (
                    "tingkat",
                    models.CharField(
                        choices=[
                            ("info", "Informasi (biru)"),
                            ("perhatian", "Perhatian (kuning)"),
                            ("penting", "Penting (merah)"),
                        ],
                        default="perhatian",
                        help_text="Menentukan warna pop-up.",
                        max_length=12,
                        verbose_name="Tingkat",
                    ),
                ),
                (
                    "mulai",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opsional. Ditampilkan di pop-up sebagai jadwal.",
                        null=True,
                        verbose_name="Mulai Pemeliharaan",
                    ),
                ),
                (
                    "selesai",
                    models.DateTimeField(
                        blank=True,
                        help_text="Opsional. Ditampilkan di pop-up sebagai jadwal.",
                        null=True,
                        verbose_name="Perkiraan Selesai",
                    ),
                ),
                (
                    "berhenti_otomatis",
                    models.BooleanField(
                        default=True,
                        help_text="Bila dicentang dan Perkiraan Selesai sudah lewat, pop-up berhenti muncul tanpa perlu dimatikan manual. Kosongkan Perkiraan Selesai bila pengumuman harus tampil sampai dimatikan.",
                        verbose_name="Berhenti Sendiri Setelah Selesai",
                    ),
                ),
                (
                    "diubah_pada",
                    models.DateTimeField(auto_now=True, verbose_name="Diubah Pada"),
                ),
                (
                    "diubah_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diubah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengumuman Pemeliharaan",
                "verbose_name_plural": "Pengumuman Pemeliharaan",
            },
        ),
    ]
