# Generated by Django 6.0.2 on 2026-08-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0064_add_asset_id_and_open_status_aset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZabbixHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zabbix_hostid",
                    models.CharField(
                        help_text='Kolom "hostid" dari Zabbix API (angka, unik per host).',
                        max_length=50,
                        unique=True,
                        verbose_name="Host ID Zabbix",
                    ),
                ),
                (
                    "zabbix_host",
                    models.CharField(
                        blank=True,
                        help_text='Kolom "host" (nama teknis) dari Zabbix.',
                        max_length=150,
                        verbose_name="Technical Name",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        help_text='Diambil dari "name" (visible name) Zabbix saat sync pertama; bisa diubah manual.',
                        max_length=150,
                        verbose_name="Nama Tampilan",
                    ),
                ),
                (
                    "lokasi",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Lokasi / Gardu"
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("PROBLEM", "Problem"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Severity Tertinggi"
                    ),
                ),
                (
                    "problem_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Problem Aktif"
                    ),
                ),
                (
                    "state_sejak",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="State Sejak"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Kapan sync_zabbix terakhir berhasil membaca host ini dari Zabbix API.",
                        null=True,
                        verbose_name="Sinkron Terakhir",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opsional — hubungkan ke data aset FASOP yang sesuai.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zabbix_hosts",
                        to="devices.device",
                        verbose_name="Perangkat FASOP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host Zabbix",
                "verbose_name_plural": "Host Zabbix",
                "ordering": ["urutan", "nama"],
            },
        ),
        migrations.CreateModel(
            name="ZabbixWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ok", models.BooleanField(default=False)),
                ("keterangan", models.CharField(blank=True, max_length=255)),
                (
                    "payload",
                    models.TextField(blank=True, verbose_name="Body JSON diterima"),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="zabbix_mon.zabbixhost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Webhook Zabbix",
                "verbose_name_plural": "Log Webhook Zabbix",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="ZabbixEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("PROBLEM", "Problem"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("severity", models.CharField(blank=True, max_length=30)),
                ("problem_name", models.CharField(blank=True, max_length=255)),
                (
                    "zabbix_eventid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Kolom "eventid" Zabbix — dipakai untuk mencegah duplikasi transisi antara sync_zabbix dan webhook.',
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "Zabbix API (pull)"),
                            ("webhook", "Zabbix Webhook (push)"),
                        ],
                        default="api",
                        max_length=10,
                    ),
                ),
                ("mulai", models.DateTimeField(db_index=True)),
                ("selesai", models.DateTimeField(blank=True, null=True)),
                ("durasi_menit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="zabbix_mon.zabbixhost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log State Host Zabbix",
                "verbose_name_plural": "Log State Host Zabbix",
                "ordering": ["-mulai"],
                "indexes": [
                    models.Index(
                        fields=["host", "-mulai"], name="zabbix_mon__host_id_c76b96_idx"
                    )
                ],
            },
        ),
    ]
