# Generated by Django 6.0.2 on 2026-08-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_mon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixhost',
            name='wa_alert',
            field=models.BooleanField(default=False, help_text='Centang agar transisi PROBLEM/pulih host ini dikirim ke grup WhatsApp lewat OpenWA. Butuh WA_ALERT_ENABLED=True di .env.', verbose_name='Blast WhatsApp'),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='wa_chat_ids',
            field=models.CharField(blank=True, help_text='Opsional — chatId tujuan khusus host ini (pisahkan koma, grup berakhiran "@g.us"). Kosongkan untuk memakai WA_CHAT_IDS_ZABBIX dari .env.', max_length=255, verbose_name='Grup WA Khusus'),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='wa_min_severity',
            field=models.CharField(choices=[('0', 'Not classified'), ('1', 'Information'), ('2', 'Warning'), ('3', 'Average'), ('4', 'High'), ('5', 'Disaster')], default='3', help_text='Blast PROBLEM hanya dikirim bila severity-nya minimal ini. Naikkan kalau grup terlalu berisik.', max_length=1, verbose_name='Severity Minimum'),
        ),
        migrations.CreateModel(
            name='ZabbixAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('PROBLEM', 'Problem'), ('OK', 'Pulih')], max_length=10)),
                ('pesan', models.TextField(verbose_name='Isi pesan')),
                ('terkirim', models.BooleanField(default=False, verbose_name='Terkirim')),
                ('keterangan', models.CharField(blank=True, max_length=255, verbose_name='Keterangan / error')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='zabbix_mon.zabbixhost')),
            ],
            options={
                'verbose_name': 'Log Blast WA Zabbix',
                'verbose_name_plural': 'Log Blast WA Zabbix',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host', '-created_at'], name='zbx_alert_host_created_idx')],
            },
        ),
    ]
