"""
Django settings for fasop project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'devices',
    'maintenance',
    'gangguan',
    'health_index',
    'notifikasi',
    'jadwal',
    'gudang',
    'inspection',
    'opsis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'devices.middleware.ForcePasswordChangeMiddleware',
    'devices.middleware.OpsisAccessMiddleware',
    'devices.middleware.OperatorAccessMiddleware',
    'devices.middleware.SingleSessionMiddleware',
]

ROOT_URLCONF = 'fasop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'devices.context_processors.device_types',
                'devices.context_processors.lokasi_list',
                'devices.context_processors.notifikasi_count',
                'devices.context_processors.user_permissions',
                'devices.context_processors.user_display_name',
                'devices.context_processors.pending_approval_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'fasop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True

USE_L10N = True
DATE_INPUT_FORMATS = ['%d-%m-%Y']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Batas ukuran upload file (default Django: 2.5 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024   # 20 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024   # 20 MB

SESSION_COOKIE_AGE            = 28800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY       = True
SESSION_COOKIE_SAMESITE       = 'Lax'
SESSION_COOKIE_SECURE         = not DEBUG   # True di production (HTTPS)

CSRF_COOKIE_HTTPONLY          = True
CSRF_COOKIE_SAMESITE          = 'Lax'
CSRF_COOKIE_SECURE            = not DEBUG   # True di production (HTTPS)

# -------------------------------------------------------------------
# Login rate limiting — django-axes
# -------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT       = 5
AXES_LOCKOUT_PARAMETERS  = [['username', 'ip_address']]   # kunci per username + IP
AXES_RESET_ON_SUCCESS    = True             # reset counter jika berhasil login
AXES_LOCKOUT_TEMPLATE    = 'registration/lockout.html'
AXES_VERBOSE             = False

# -------------------------------------------------------------------
# API Key untuk integrasi eksternal (n8n, Google Sheets, dsb.)
# Set di .env:  API_KEY=isi-dengan-string-acak-yang-kuat
# -------------------------------------------------------------------
API_KEY = config('API_KEY', default='')

# -------------------------------------------------------------------
# MSSQL — Koneksi ke database historian/SCADA untuk fitur Opsis
# Set di .env server (tidak di-commit):
#   MSSQL_HOST=localhost
#   MSSQL_DB=nama_database
#   MSSQL_USER=username
#   MSSQL_PASS=password
#   MSSQL_DRIVER=ODBC Driver 17 for SQL Server
# -------------------------------------------------------------------
MSSQL_HOST   = config('MSSQL_HOST',   default='')
MSSQL_DB     = config('MSSQL_DB',     default='')
MSSQL_USER   = config('MSSQL_USER',   default='')
MSSQL_PASS   = config('MSSQL_PASS',   default='')
MSSQL_TABLE    = config('MSSQL_TABLE',    default='dbo.HIS_MEAS_KIT')
MSSQL_RT_TABLE = config('MSSQL_RT_TABLE', default='dbo.KIT_REALTIME')
MSSQL_FREQ_TABLE = config('MSSQL_FREQ_TABLE', default='dbo.SYS_FREQ_HIS')
MSSQL_DRIVER   = config('MSSQL_DRIVER',   default='ODBC Driver 17 for SQL Server')


