# Generated by Django 6.0.2 on 2026-06-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_created_4d7322_idx',
            old_name='auditlog_au_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_user_id_08ad03_idx',
            old_name='auditlog_au_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_action_4744c0_idx',
            old_name='auditlog_au_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_app_lab_a37db8_idx',
            old_name='auditlog_au_app_idx',
        ),
    ]
