# Generated by Django 6.0.2 on 2026-02-20 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_rename_attachment_maintenance_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MaintenancePLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akses_plc', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('remote_akses_plc', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('transmission_line', models.FloatField(blank=True, null=True)),
                ('rx_pilot_level', models.FloatField(blank=True, null=True)),
                ('time_sync', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('wave_trap', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('imu', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('kabel_coaxial', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenance')),
            ],
        ),
    ]
