# Generated by Django 6.0.2 on 2026-03-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenanceplc_freq_bandwidth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='maintenanceplc',
            options={'verbose_name': 'Maintenance PLC'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerouter',
            options={'verbose_name': 'Maintenance Router/Switch'},
        ),
        migrations.AlterField(
            model_name='maintenancerouter',
            name='detail_port',
            field=models.TextField(blank=True, verbose_name='Detail Status Port'),
        ),
        migrations.AlterField(
            model_name='maintenancerouter',
            name='jumlah_port_aktif',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Port Aktif'),
        ),
        migrations.AlterField(
            model_name='maintenancerouter',
            name='jumlah_port_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Port Total'),
        ),
        migrations.AlterField(
            model_name='maintenancerouter',
            name='status_routing',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3, verbose_name='IP / Routing Status'),
        ),
        migrations.AlterField(
            model_name='maintenancerouter',
            name='tegangan_input',
            field=models.FloatField(blank=True, null=True, verbose_name='Tegangan Input (V)'),
        ),
    ]
