# Generated by Django 6.0.2 on 2026-07-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_enemy', '0002_alter_commonenemy_catatan_penutupan_and_more'),
        ('devices', '0056_alter_branch_id_alter_devicelink_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonenemy',
            name='peralatan',
            field=models.ForeignKey(blank=True, help_text='Opsional — pilih peralatan spesifik', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_enemy_terkait', to='devices.device', verbose_name='Peralatan Terdampak'),
        ),
        migrations.AlterField(
            model_name='commonenemy',
            name='sub_kategori',
            field=models.ForeignKey(blank=True, help_text='Opsional — pilih jenis peralatan sesuai bidang', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_enemy_terkait', to='devices.devicetype', verbose_name='Sub Kategori (Jenis Peralatan)'),
        ),
        migrations.AlterField(
            model_name='commonenemy',
            name='tindak_lanjut',
            field=models.TextField(blank=True, help_text='Tindakan yang sudah / sedang dilakukan', verbose_name='Tindak Lanjut'),
        ),
    ]
