# Generated by Django 6.0.2 on 2026-04-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspection_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='jenis',
            field=models.CharField(choices=[('catu_daya', 'Catu Daya'), ('defense_scheme', 'Rele Defense Scheme'), ('master_trip', 'Master Trip'), ('ufls', 'UFLS')], max_length=30, verbose_name='Jenis Inspeksi'),
        ),
        migrations.AlterField(
            model_name='inspectiondefensescheme',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
        migrations.AlterField(
            model_name='inspectionmastertrip',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
        migrations.AlterField(
            model_name='inspectionufls',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
    ]
