# Generated by Django 6.0.2 on 2026-06-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_alter_inspection_jenis_and_more'),
        ('inspection', '0008_pengujiantelecom_jenis'),
    ]

    operations = [
    ]
