# Generated by Django 6.0.2 on 2026-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_pengujiantelecom_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiondefensescheme',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
        migrations.AlterField(
            model_name='inspectionmastertrip',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
        migrations.AlterField(
            model_name='inspectionufls',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
    ]
