# Generated by Django 6.0.2 on 2026-07-02 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_alter_inspectiondefensescheme_suhu_ruangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiondefensescheme',
            name='kelembapan',
            field=models.FloatField(blank=True, null=True, verbose_name='Kelembapan (%)'),
        ),
        migrations.AddField(
            model_name='inspectionmastertrip',
            name='kelembapan',
            field=models.FloatField(blank=True, null=True, verbose_name='Kelembapan (%)'),
        ),
        migrations.AddField(
            model_name='inspectionufls',
            name='kelembapan',
            field=models.FloatField(blank=True, null=True, verbose_name='Kelembapan (%)'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='jenis',
            field=models.CharField(choices=[('catu_daya', 'Catu Daya'), ('defense_scheme', 'Rele Defense Scheme'), ('master_trip', 'Master Trip'), ('ufls', 'UFLS'), ('dfr', 'DFR'), ('server_ads', 'Server ADS'), ('telecom', 'Pengujian Telekomunikasi')], max_length=30, verbose_name='Jenis Inspeksi'),
        ),
        migrations.CreateModel(
            name='InspectionDFR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu_ruangan', models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)')),
                ('kelembapan', models.FloatField(blank=True, null=True, verbose_name='Kelembapan (%)')),
                ('kebersihan_ruangan', models.CharField(blank=True, choices=[('bersih', 'Bersih'), ('kotor', 'Kotor')], max_length=10, verbose_name='Kebersihan')),
                ('lampu_penerangan', models.CharField(blank=True, choices=[('baik', 'Baik'), ('tidak_berfungsi', 'Tidak Berfungsi'), ('redup', 'Redup')], max_length=20, verbose_name='Lampu Penerangan')),
                ('kondisi_dfr', models.CharField(blank=True, choices=[('normal', 'Normal'), ('faulty', 'Faulty')], max_length=15, verbose_name='Kondisi DFR')),
                ('healthy_status', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('faulty', 'Faulty'), ('alarm', 'Alarm')], max_length=10, verbose_name='Healthy Status')),
                ('indikasi_led_alarm', models.CharField(blank=True, choices=[('ada', 'Ada'), ('tidak_ada', 'Tidak Ada')], max_length=10, verbose_name='Indikasi LED Alarm')),
                ('status_indikator', models.CharField(blank=True, choices=[('normal', 'Normal'), ('tidak_normal', 'Tidak Normal')], max_length=15, verbose_name='Status Indikator')),
                ('kondisi_kabel_lan', models.CharField(blank=True, choices=[('normal', 'Normal'), ('terlepas', 'Terlepas')], max_length=10, verbose_name='Kondisi Kabel LAN')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_dfr', to='inspection.inspection')),
            ],
            options={
                'verbose_name': 'Detail Inspeksi DFR',
            },
        ),
        migrations.CreateModel(
            name='InspectionServerADS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu_ruangan', models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)')),
                ('kelembapan', models.FloatField(blank=True, null=True, verbose_name='Kelembapan (%)')),
                ('kebersihan_ruangan', models.CharField(blank=True, choices=[('bersih', 'Bersih'), ('kotor', 'Kotor')], max_length=10, verbose_name='Kebersihan')),
                ('lampu_penerangan', models.CharField(blank=True, choices=[('baik', 'Baik'), ('tidak_berfungsi', 'Tidak Berfungsi'), ('redup', 'Redup')], max_length=20, verbose_name='Lampu Penerangan')),
                ('peralatan_server_ads', models.CharField(blank=True, choices=[('normal', 'Normal'), ('tidak_normal', 'Tidak Normal')], max_length=15, verbose_name='Peralatan Server ADS')),
                ('tampilan_hmi', models.CharField(blank=True, choices=[('normal', 'Normal'), ('tidak_normal', 'Tidak Normal'), ('tidak_tersedia', 'Tidak Tersedia')], max_length=20, verbose_name='Tampilan HMI')),
                ('peralatan_gateway_ic3', models.CharField(blank=True, choices=[('normal', 'Normal'), ('tidak_normal', 'Tidak Normal')], max_length=15, verbose_name='Peralatan Gateway IC3 ADS')),
                ('kondisi_switch_lan', models.CharField(blank=True, choices=[('normal', 'Normal'), ('mati', 'Mati')], max_length=10, verbose_name='Kondisi Switch Kabel LAN')),
                ('peralatan_power_supply', models.CharField(blank=True, choices=[('normal', 'Normal'), ('tidak_normal', 'Tidak Normal')], max_length=15, verbose_name='Peralatan Power Supply')),
                ('fan_panel', models.CharField(blank=True, choices=[('nyala', 'Nyala'), ('mati', 'Mati')], max_length=10, verbose_name='Fan Panel')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_server_ads', to='inspection.inspection')),
            ],
            options={
                'verbose_name': 'Detail Inspeksi Server ADS',
            },
        ),
    ]
