# Generated by Django 6.0.2 on 2026-07-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_inspectiondefensescheme_kelembapan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionmastertrip',
            name='kondisi_kabel_lan',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('terlepas', 'Terlepas')], max_length=20, verbose_name='Kondisi Kabel LAN'),
        ),
        migrations.AlterField(
            model_name='inspectionmastertrip',
            name='posisi_selektor',
            field=models.CharField(blank=True, choices=[('blok', 'Blok'), ('on', 'ON')], max_length=15, verbose_name='Posisi Selektor Target'),
        ),
    ]
