# Generated by Django 6.0.2 on 2026-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_alter_inspectionmastertrip_kondisi_kabel_lan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiondefensescheme',
            name='selektor_blok_skema',
            field=models.CharField(blank=True, choices=[('on', 'ON'), ('off', 'OFF')], max_length=5, verbose_name='Selektor Blok Skema'),
        ),
        migrations.AddField(
            model_name='inspectiondefensescheme',
            name='status_indikator',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('tidak_normal', 'Tidak Normal')], max_length=15, verbose_name='Status Indikator'),
        ),
        migrations.AlterField(
            model_name='inspectiondefensescheme',
            name='kondisi_kabel_lan',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('terlepas', 'Terlepas')], max_length=20, verbose_name='Kondisi Kabel LAN'),
        ),
        migrations.AlterField(
            model_name='inspectiondefensescheme',
            name='posisi_selektor',
            field=models.CharField(blank=True, choices=[('blok', 'Blok'), ('on', 'ON')], max_length=15, verbose_name='Posisi Selektor Target'),
        ),
    ]
