# Generated by Django 6.0.2 on 2026-07-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0012_inspectiondefensescheme_selektor_blok_skema_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectiondefensescheme",
            name="indikator_led",
        ),
        migrations.RemoveField(
            model_name="inspectiondefensescheme",
            name="relay_healthy",
        ),
        migrations.RemoveField(
            model_name="inspectionmastertrip",
            name="relay_healthy",
        ),
        migrations.RemoveField(
            model_name="inspectionufls",
            name="relay_healthy",
        ),
        migrations.AlterField(
            model_name="inspectiondefensescheme",
            name="kondisi_relay",
            field=models.CharField(
                blank=True,
                choices=[("normal", "Normal"), ("alarm", "Alarm")],
                max_length=15,
                verbose_name="Kondisi Rele",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionmastertrip",
            name="indikator_led",
            field=models.CharField(
                blank=True,
                choices=[("normal", "Normal"), ("tidak_normal", "Tidak Normal")],
                max_length=15,
                verbose_name="Status Indikator",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionmastertrip",
            name="kondisi_relay",
            field=models.CharField(
                blank=True,
                choices=[("normal", "Normal"), ("alarm", "Alarm")],
                max_length=15,
                verbose_name="Kondisi Rele",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionufls",
            name="indikator_led",
            field=models.CharField(
                blank=True,
                choices=[("normal", "Normal"), ("tidak_normal", "Tidak Normal")],
                max_length=15,
                verbose_name="Status Indikator",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionufls",
            name="kondisi_relay",
            field=models.CharField(
                blank=True,
                choices=[("normal", "Normal"), ("alarm", "Alarm")],
                max_length=15,
                verbose_name="Kondisi Rele",
            ),
        ),
    ]
