# Generated by Django 6.0.2 on 2026-07-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_merge_20260604_1138'),
        ('inspection', '0012_inspectiondefensescheme_selektor_blok_skema_and_more'),
    ]

    operations = [
    ]
