# Generated by Django 6.0.2 on 2026-07-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0013_merge_20260702_1658'),
        ('inspection', '0013_remove_inspectiondefensescheme_indikator_led_and_more'),
    ]

    operations = [
    ]
