# Generated by Django 6.0.2 on 2026-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_merge_20260703_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='jenis',
            field=models.CharField(choices=[('catu_daya', 'Catu Daya'), ('defense_scheme', 'Rele Defense Scheme'), ('master_trip', 'Master Trip'), ('ufls', 'UFLS'), ('dfr', 'DFR'), ('server_ads', 'Server ADS'), ('telecom', 'Pengujian Telekomunikasi')], max_length=30, verbose_name='Jenis Inspeksi'),
        ),
    ]
