# Generated by Django 6.0.2 on 2026-08-13 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0015_alter_inspection_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField(verbose_name='Isi pesan')),
                ('terkirim', models.BooleanField(default=False, verbose_name='Terkirim')),
                ('keterangan', models.CharField(blank=True, max_length=255, verbose_name='Keterangan / error')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='inspection.inspection')),
            ],
            options={
                'verbose_name': 'Log Alarm WA Inspeksi',
                'verbose_name_plural': 'Log Alarm WA Inspeksi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inspection', '-created_at'], name='insp_alert_log_idx')],
            },
        ),
    ]
