# Generated by Django 6.0.2 on 2026-08-13 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_mon', '0002_rtualertlog'),
        ('devices', '0064_add_asset_id_and_open_status_aset'),
        ('inspection', '0016_inspectionalertlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KesiapanFasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=200, verbose_name='Judul Laporan')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Umum / Lain-Lain')),
                ('public_token', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Token Publik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('pelaksana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kesiapan_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Pelaksana')),
            ],
            options={
                'verbose_name': 'Laporan Kesiapan Fasilitas Operasi',
                'verbose_name_plural': 'Laporan Kesiapan Fasilitas Operasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KesiapanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seksi', models.CharField(choices=[('remote_station', 'Remote Station'), ('master_station', 'Master Station'), ('telekomunikasi', 'Telekomunikasi'), ('catu_daya', 'Catu Daya'), ('proteksi_sistem', 'Proteksi Sistem')], max_length=20, verbose_name='Seksi')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Perangkat')),
                ('lokasi', models.CharField(blank=True, max_length=100, verbose_name='Lokasi')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('gangguan', 'Gangguan')], default='normal', max_length=10, verbose_name='Status')),
                ('keterangan', models.CharField(blank=True, max_length=300, verbose_name='Keterangan')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kesiapan_items', to='devices.device')),
                ('kesiapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspection.kesiapanfasilitas')),
                ('source_rtu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kesiapan_items', to='device_mon.rtu')),
            ],
            options={
                'verbose_name': 'Item Kesiapan',
                'verbose_name_plural': 'Item Kesiapan',
                'ordering': ['seksi', 'urutan', 'id'],
            },
        ),
    ]
