# Generated by Django 6.0.2 on 2026-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0017_kesiapanfasilitas_kesiapanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesiapanitem',
            name='kondisi',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('ON', 'ON'), ('TR', 'TR'), ('NC', 'NC'), ('SB', 'SB'), ('AVAILABLE', 'AVAILABLE')], max_length=15, verbose_name='Kondisi Master Station'),
        ),
    ]
