# Generated by Django 6.0.2 on 2026-08-13 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0018_kesiapanitem_kondisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kesiapanfasilitas',
            name='is_selesai',
            field=models.BooleanField(default=False, verbose_name='Selesai'),
        ),
        migrations.AddField(
            model_name='kesiapanfasilitas',
            name='selesai_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai'),
        ),
        migrations.AddField(
            model_name='kesiapanfasilitas',
            name='selesai_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kesiapan_diselesaikan', to=settings.AUTH_USER_MODEL, verbose_name='Diselesaikan oleh'),
        ),
    ]
