# Generated by Django 6.0.2 on 2026-03-26 00:54

import django.db.models.deletion
import gangguan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_device_foto_alter_device_foto2_and_more'),
        ('gangguan', '0007_gangguan_pelaksana_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='gangguan',
            name='komponen_rusak',
            field=models.ForeignKey(blank=True, help_text='Opsional — pilih komponen spesifik yang rusak (misal: Modul CPU Slot A)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gangguan_terkait', to='devices.devicecomponent', verbose_name='Komponen Rusak'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='catatan_penutupan',
            field=models.TextField(blank=True, help_text='Diisi saat gangguan dinyatakan selesai / closed', verbose_name='Catatan Penutupan'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='dampak_gangguan',
            field=models.TextField(help_text='Dampak yang ditimbulkan terhadap layanan/sistem', verbose_name='Dampak Gangguan'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='executive_summary',
            field=models.TextField(help_text='Ringkasan singkat kondisi gangguan', verbose_name='Executive Summary'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='foto_eviden1',
            field=models.ImageField(blank=True, null=True, upload_to=gangguan.models.eviden1_upload, verbose_name='Foto Eviden 1'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='foto_eviden2',
            field=models.ImageField(blank=True, null=True, upload_to=gangguan.models.eviden2_upload, verbose_name='Foto Eviden 2'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='foto_eviden3',
            field=models.ImageField(blank=True, null=True, upload_to=gangguan.models.eviden3_upload, verbose_name='Foto Eviden 3'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='indikasi_gangguan',
            field=models.TextField(help_text='Gejala atau indikasi yang terdeteksi', verbose_name='Indikasi Gangguan'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='penyebab_gangguan',
            field=models.TextField(blank=True, help_text='Root cause gangguan jika sudah diketahui', verbose_name='Penyebab Gangguan'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='peralatan',
            field=models.ForeignKey(blank=True, help_text='Opsional — pilih peralatan spesifik jika gangguan terkait satu perangkat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='Peralatan Terdampak'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='site',
            field=models.CharField(help_text='Nama site yang mengalami gangguan', max_length=150, verbose_name='Site / Lokasi'),
        ),
        migrations.AlterField(
            model_name='gangguan',
            name='tindak_lanjut',
            field=models.TextField(blank=True, help_text='[Tidak digunakan lagi — gunakan Log Tindak Lanjut]', verbose_name='Tindak Lanjut'),
        ),
    ]
