# Generated by Django 6.0.2 on 2026-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangguan', '0010_gangguan_fiber_optic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gangguan',
            name='tipe_gangguan',
            field=models.CharField(choices=[('device', 'Gangguan Device / Perangkat'), ('link', 'Gangguan Link / Fiber Optic')], default='device', max_length=10, verbose_name='Tipe Gangguan'),
        ),
    ]
