# Generated by Django 6.0.2 on 2026-08-07 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0061_db_indexes'),
        ('gangguan', '0011_alter_gangguan_tipe_gangguan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gangguan',
            index=models.Index(fields=['status', '-tanggal_gangguan'], name='gangguan_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='gangguan',
            index=models.Index(fields=['site', '-tanggal_gangguan'], name='gangguan_site_date_idx'),
        ),
        migrations.AddIndex(
            model_name='gangguan',
            index=models.Index(fields=['tipe_gangguan', '-tanggal_gangguan'], name='gangguan_tipe_date_idx'),
        ),
    ]
