# Generated by Django 6.0.2 on 2026-05-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentasi', '0004_settingrele_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambardevice',
            name='versi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Versi / Revisi'),
        ),
        migrations.AlterField(
            model_name='settingrele',
            name='versi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Versi / Revisi'),
        ),
    ]
