# Generated by Django 6.0.2 on 2026-08-07 01:10

import django.core.validators
import dokumentasi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumentasi', '0005_alter_gambardevice_versi_alter_settingrele_versi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambardevice',
            name='file_gambar',
            field=models.FileField(blank=True, null=True, upload_to=dokumentasi.models.gambar_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), dokumentasi.models.validate_dokumentasi_file_size], verbose_name='File Gambar'),
        ),
        migrations.AlterField(
            model_name='settingrele',
            name='file_setting',
            field=models.FileField(blank=True, null=True, upload_to=dokumentasi.models.setting_file_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), dokumentasi.models.validate_dokumentasi_file_size], verbose_name='File Setting'),
        ),
    ]
