# Generated by Django 6.0.2 on 2026-02-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='attachment',
            new_name='photo',
        ),
    ]
