# Generated by Django 6.0.2 on 2026-03-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_multi_technician_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancemux',
            name='psu1_temp1',
            field=models.FloatField(blank=True, null=True, verbose_name='PSU1 Temp Sensor 1 (°C)'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='psu1_temp2',
            field=models.FloatField(blank=True, null=True, verbose_name='PSU1 Temp Sensor 2 (°C)'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='psu1_temp3',
            field=models.FloatField(blank=True, null=True, verbose_name='PSU1 Temp Sensor 3 (°C)'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='psu2_temp1',
            field=models.FloatField(blank=True, null=True, verbose_name='PSU2 Temp Sensor 1 (°C)'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='psu2_temp2',
            field=models.FloatField(blank=True, null=True, verbose_name='PSU2 Temp Sensor 2 (°C)'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='psu2_temp3',
            field=models.FloatField(blank=True, null=True, verbose_name='PSU2 Temp Sensor 3 (°C)'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_a_isian',
            field=models.TextField(blank=True, verbose_name='Slot A Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_a_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot A Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_b_isian',
            field=models.TextField(blank=True, verbose_name='Slot B Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_b_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot B Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_c_isian',
            field=models.TextField(blank=True, verbose_name='Slot C Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_c_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot C Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_d_isian',
            field=models.TextField(blank=True, verbose_name='Slot D Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_d_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot D Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_e_isian',
            field=models.TextField(blank=True, verbose_name='Slot E Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_e_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot E Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_f_isian',
            field=models.TextField(blank=True, verbose_name='Slot F Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_f_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot F Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_g_isian',
            field=models.TextField(blank=True, verbose_name='Slot G Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_g_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot G Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_h_isian',
            field=models.TextField(blank=True, verbose_name='Slot H Isian'),
        ),
        migrations.AlterField(
            model_name='maintenancemux',
            name='slot_h_modul',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slot H Modul'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='bat1_air_battery',
            field=models.FloatField(blank=True, null=True, verbose_name='Air Battery Bank 1 (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='bat1_cells',
            field=models.JSONField(blank=True, default=list, verbose_name='Data Cell Bank 1'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='bat1_jumlah',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Cell Bank 1'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='bat1_v_load',
            field=models.FloatField(blank=True, null=True, verbose_name='V Load Bank 1 (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='bat1_v_total',
            field=models.FloatField(blank=True, null=True, verbose_name='V Total Bank 1 (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_a_battery',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 Arus Battery (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_a_load',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 Arus Load (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_a_rectifier',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 Arus Rectifier (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_teg_neg_ground',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 Teg(-) Ground (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_teg_pos_ground',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 Teg(+) Ground (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_v_battery',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 V Battery (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_v_dropper',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 Dropper (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='rect1_v_rectifier',
            field=models.FloatField(blank=True, null=True, verbose_name='Rect1 V Rectifier (V)'),
        ),
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='suhu_ruangan',
            field=models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)'),
        ),
    ]
