# Generated by Django 6.0.2 on 2026-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_alter_maintenancemux_psu1_temp1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
