# Generated by Django 6.0.2 on 2026-03-26 00:54

import django.db.models.deletion
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_device_foto_alter_device_foto2_and_more'),
        ('maintenance', '0022_maintenancecorrective'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecorrective',
            name='komponen_terkait',
            field=models.ForeignKey(blank=True, help_text='Pilih komponen spesifik yang diperbaiki/diganti', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_maintenances', to='devices.devicecomponent', verbose_name='Komponen Terkait'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=maintenance.models.maintenance_photo_upload),
        ),
        migrations.AlterField(
            model_name='maintenancecorrective',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
