# Generated by Django 6.0.2 on 2026-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_maintenancegenset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancegenset',
            name='tangki_bbm_sebelum',
            field=models.FloatField(blank=True, null=True, verbose_name='Tangki BBM Sebelum (%)'),
        ),
        migrations.AlterField(
            model_name='maintenancegenset',
            name='tangki_bbm_sesudah',
            field=models.FloatField(blank=True, null=True, verbose_name='Tangki BBM Sesudah (%)'),
        ),
    ]
