# Generated by Django 6.0.2 on 2026-04-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_maintenancertu_ps48_arus_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerectifier',
            name='catatan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
