# Generated by Django 6.0.2 on 2026-04-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0036_maintenanceups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceups',
            name='bat_kondisi',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3, verbose_name='Kondisi Battery'),
        ),
        migrations.AlterField(
            model_name='maintenanceups',
            name='bat_kondisi_kabel',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3, verbose_name='Kondisi Kabel Battery'),
        ),
        migrations.AlterField(
            model_name='maintenanceups',
            name='ups_kondisi',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3, verbose_name='Kondisi UPS'),
        ),
    ]
