# Generated by Django 6.0.2 on 2026-04-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0037_alter_maintenanceups_bat_kondisi_and_more'),
        ('maintenance', '0037_beritaacararecord_beritaacaraeviden'),
    ]

    operations = [
    ]
