# Generated by Django 6.0.2 on 2026-04-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0038_beritaacararecord_ttd_fields'),
        ('maintenance', '0038_merge_20260416_1455'),
    ]

    operations = [
    ]
