# Generated by Django 6.0.2 on 2026-05-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0038_beritaacararecord_ttd_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritaacararecord',
            name='jenis',
            field=models.CharField(choices=[('pemasangan', 'Pemasangan'), ('pembongkaran', 'Pembongkaran'), ('penggantian', 'Penggantian'), ('gangguan', 'Gangguan')], max_length=20),
        ),
    ]
