# Generated by Django 6.0.2 on 2026-05-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0039_merge_20260418_0814'),
        ('maintenance', '0040_beritaacararecord_jenis_gangguan'),
    ]

    operations = [
    ]
