from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0040_beritaacararecord_jenis_gangguan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFrequencyRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Visual Inspection
                ('healthy',  models.CharField(blank=True, max_length=10, choices=[('Normal','Normal'),('Abnormal','Abnormal')], verbose_name='Healthy')),
                ('frek_oor', models.CharField(blank=True, max_length=10, choices=[('Normal','Normal'),('Abnormal','Abnormal')], verbose_name='Frek Out of Range')),
                ('alarm',    models.CharField(blank=True, max_length=10, choices=[('Normal','Normal'),('Abnormal','Abnormal')], verbose_name='Alarm')),
                # Info Relay
                ('fungsi',          models.CharField(blank=True, max_length=20, choices=[('UFLS','UFLS'),('UFR ISLAND','UFR ISLAND'),('OFGS','OFGS'),('CDSAS','CDSAS')], verbose_name='Fungsi')),
                ('target_proteksi', models.CharField(blank=True, max_length=20, choices=[('TRAFO','TRAFO'),('LINE','LINE'),('TRAFO / LINE','TRAFO / LINE')], verbose_name='Target Proteksi')),
                ('rasio_vt',     models.CharField(blank=True, max_length=30, verbose_name='Rasio VT (Primer)')),
                ('rasio_vt_sek', models.CharField(blank=True, max_length=30, verbose_name='Rasio VT (Sekunder)')),
                ('vblock',       models.CharField(blank=True, max_length=30, verbose_name='*Vblock')),
                # Measurement
                ('v_an',  models.CharField(blank=True, max_length=15, verbose_name='V An (kV)')),
                ('v_bn',  models.CharField(blank=True, max_length=15, verbose_name='V Bn (kV)')),
                ('v_cn',  models.CharField(blank=True, max_length=15, verbose_name='V Cn (kV)')),
                ('v_ab',  models.CharField(blank=True, max_length=15, verbose_name='V AB (kV)')),
                ('v_bc',  models.CharField(blank=True, max_length=15, verbose_name='V BC (kV)')),
                ('v_ac',  models.CharField(blank=True, max_length=15, verbose_name='V AC (kV)')),
                ('frekuensi', models.CharField(blank=True, max_length=15, verbose_name='Frekuensi (Hz)')),
                ('target_v_an',      models.CharField(blank=True, max_length=30, verbose_name='Target V An')),
                ('target_v_bn',      models.CharField(blank=True, max_length=30, verbose_name='Target V Bn')),
                ('target_v_cn',      models.CharField(blank=True, max_length=30, verbose_name='Target V Cn')),
                ('target_v_ab',      models.CharField(blank=True, max_length=30, verbose_name='Target V AB')),
                ('target_v_bc',      models.CharField(blank=True, max_length=30, verbose_name='Target V BC')),
                ('target_v_ac',      models.CharField(blank=True, max_length=30, verbose_name='Target V AC')),
                ('target_frekuensi', models.CharField(blank=True, max_length=30, verbose_name='Target Frekuensi')),
                # Setting F1-F7
                ('f1_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F1 Frekuensi (Hz)')),
                ('f1_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F1 Waktu (s)')),
                ('f1_rl',      models.CharField(blank=True, max_length=10, verbose_name='F1 RL No')),
                ('f1_pos_vdc', models.CharField(blank=True, max_length=15, verbose_name='F1 Common(+) vDC')),
                ('f1_pos_pin', models.CharField(blank=True, max_length=15, verbose_name='F1 Common(+) Pin')),
                ('f1_neg_vdc', models.CharField(blank=True, max_length=15, verbose_name='F1 Common(−) vDC')),
                ('f1_neg_pin', models.CharField(blank=True, max_length=15, verbose_name='F1 Common(−) Pin')),
                ('f2_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F2 Frekuensi (Hz)')),
                ('f2_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F2 Waktu (s)')),
                ('f2_rl',      models.CharField(blank=True, max_length=10)),
                ('f2_pos_vdc', models.CharField(blank=True, max_length=15)),
                ('f2_pos_pin', models.CharField(blank=True, max_length=15)),
                ('f2_neg_vdc', models.CharField(blank=True, max_length=15)),
                ('f2_neg_pin', models.CharField(blank=True, max_length=15)),
                ('f3_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F3 Frekuensi (Hz)')),
                ('f3_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F3 Waktu (s)')),
                ('f3_rl',      models.CharField(blank=True, max_length=10)),
                ('f3_pos_vdc', models.CharField(blank=True, max_length=15)),
                ('f3_pos_pin', models.CharField(blank=True, max_length=15)),
                ('f3_neg_vdc', models.CharField(blank=True, max_length=15)),
                ('f3_neg_pin', models.CharField(blank=True, max_length=15)),
                ('f4_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F4 Frekuensi (Hz)')),
                ('f4_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F4 Waktu (s)')),
                ('f4_rl',      models.CharField(blank=True, max_length=10)),
                ('f4_pos_vdc', models.CharField(blank=True, max_length=15)),
                ('f4_pos_pin', models.CharField(blank=True, max_length=15)),
                ('f4_neg_vdc', models.CharField(blank=True, max_length=15)),
                ('f4_neg_pin', models.CharField(blank=True, max_length=15)),
                ('f5_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F5 Frekuensi (Hz)')),
                ('f5_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F5 Waktu (s)')),
                ('f5_rl',      models.CharField(blank=True, max_length=10)),
                ('f5_pos_vdc', models.CharField(blank=True, max_length=15)),
                ('f5_pos_pin', models.CharField(blank=True, max_length=15)),
                ('f5_neg_vdc', models.CharField(blank=True, max_length=15)),
                ('f5_neg_pin', models.CharField(blank=True, max_length=15)),
                ('f6_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F6 Frekuensi (Hz)')),
                ('f6_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F6 Waktu (s)')),
                ('f6_rl',      models.CharField(blank=True, max_length=10)),
                ('f6_pos_vdc', models.CharField(blank=True, max_length=15)),
                ('f6_pos_pin', models.CharField(blank=True, max_length=15)),
                ('f6_neg_vdc', models.CharField(blank=True, max_length=15)),
                ('f6_neg_pin', models.CharField(blank=True, max_length=15)),
                ('f7_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='F7 Frekuensi (Hz)')),
                ('f7_s',  models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F7 Waktu (s)')),
                ('f7_rl',      models.CharField(blank=True, max_length=10)),
                ('f7_pos_vdc', models.CharField(blank=True, max_length=15)),
                ('f7_pos_pin', models.CharField(blank=True, max_length=15)),
                ('f7_neg_vdc', models.CharField(blank=True, max_length=15)),
                ('f7_neg_pin', models.CharField(blank=True, max_length=15)),
                # AUX RL
                ('aux1_rl', models.CharField(blank=True, max_length=20)),
                ('aux1_tf', models.CharField(blank=True, max_length=50)),
                ('aux1_led', models.CharField(blank=True, max_length=50)),
                ('aux2_rl', models.CharField(blank=True, max_length=20)),
                ('aux2_tf', models.CharField(blank=True, max_length=50)),
                ('aux2_led', models.CharField(blank=True, max_length=50)),
                ('aux3_rl', models.CharField(blank=True, max_length=20)),
                ('aux3_tf', models.CharField(blank=True, max_length=50)),
                ('aux3_led', models.CharField(blank=True, max_length=50)),
                ('aux4_rl', models.CharField(blank=True, max_length=20)),
                ('aux4_tf', models.CharField(blank=True, max_length=50)),
                ('aux4_led', models.CharField(blank=True, max_length=50)),
                ('aux5_rl', models.CharField(blank=True, max_length=20)),
                ('aux5_tf', models.CharField(blank=True, max_length=50)),
                ('aux5_led', models.CharField(blank=True, max_length=50)),
                ('aux6_rl', models.CharField(blank=True, max_length=20)),
                ('aux6_tf', models.CharField(blank=True, max_length=50)),
                ('aux6_led', models.CharField(blank=True, max_length=50)),
                ('aux7_rl', models.CharField(blank=True, max_length=20)),
                ('aux7_tf', models.CharField(blank=True, max_length=50)),
                ('aux7_led', models.CharField(blank=True, max_length=50)),
                # Catatan
                ('supply_dc', models.CharField(blank=True, max_length=100, verbose_name='*Supply DC')),
                ('selektor',  models.CharField(blank=True, max_length=100, verbose_name='*Selektor')),
                ('catatan',   models.TextField(blank=True, verbose_name='Catatan / Saran Perbaikan')),
                # FK
                ('maintenance', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='maintenancefrequencyrelay',
                    to='maintenance.maintenance',
                )),
            ],
            options={
                'verbose_name': 'Maintenance Frequency Relay (UFLS/UFR/OFGS/CDSAS)',
            },
        ),
    ]
