# Generated by Django 6.0.2 on 2026-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0039_teleproteksi_teg_standby_polaritas'),
        ('maintenance', '0041_merge_20260505_0912'),
    ]

    operations = [
    ]
