# Generated by Django 6.0.2 on 2026-05-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0041_maintenancefrequencyrelay'),
        ('maintenance', '0042_merge_20260505_2022'),
    ]

    operations = [
    ]
