# Generated by Django 6.0.2 on 2026-05-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0042_maintenancemastertrip'),
        ('maintenance', '0043_merge_20260508_1151'),
    ]

    operations = [
    ]
