# Generated by Django 6.0.2 on 2026-05-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0043_maintenancedfr'),
        ('maintenance', '0044_merge_20260518_1221'),
    ]

    operations = [
    ]
