# Generated by Django 6.0.2 on 2026-06-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0045_merge_0043_maintenancedfr_0044_merge_20260518_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedfr',
            name='catatan_khusus',
            field=models.TextField(blank=True, verbose_name='Catatan Khusus DFR'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='conv_rx',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='Converter Rx'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='conv_tx',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='Converter Tx'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='dfr_aktif',
            field=models.CharField(blank=True, choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], default='Ya', max_length=5, verbose_name='DFR Aktif'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='fisik_alarm',
            field=models.CharField(blank=True, choices=[('Baik', 'Baik'), ('Ada Alarm', 'Ada Alarm')], default='Baik', max_length=15, verbose_name='Pemeriksaan Fisik & Alarm'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='fo_rx',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='FO Rx'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='fo_tx',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='FO Tx'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='front_port_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='Front Port IP'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='fungsi_rekaman',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='Pemeriksaan Fungsi Rekaman'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='indoor_panel',
            field=models.CharField(blank=True, choices=[('Bersih', 'Bersih'), ('Kotor', 'Kotor')], default='Bersih', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='kapasitas_memory',
            field=models.CharField(blank=True, max_length=30, verbose_name='Kapasitas Memory DFR'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='kartu_kontrol',
            field=models.CharField(blank=True, choices=[('Terisi', 'Terisi'), ('Tidak', 'Tidak')], default='Terisi', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='kondisi_gps',
            field=models.CharField(blank=True, choices=[('Terhubung', 'Terhubung'), ('No Koneksi', 'No Koneksi')], default='Terhubung', max_length=15, verbose_name='Kondisi Koneksi GPS'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='kondisi_lcd',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='Kondisi LCD dan Keypad'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='lan_rx',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='LAN Rx'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='lan_tx',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='LAN Tx'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='outdoor_panel',
            field=models.CharField(blank=True, choices=[('Bersih', 'Bersih'), ('Kotor', 'Kotor')], default='Bersih', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='ping_dfr_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ping DFR #1 (ms)'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='ping_dfr_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ping DFR #2 (ms)'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='ping_dfr_status',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='Ping DFR Status'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='ping_server_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ping Server #1 (ms)'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='ping_server_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ping Server #2 (ms)'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='ping_server_status',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], default='Normal', max_length=10, verbose_name='Ping Server Status'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='pmu_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='PMU ID'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='rear_port_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rear Port IP'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='rekaman_gangguan',
            field=models.CharField(blank=True, choices=[('Terdownload', 'Terdownload'), ('Tidak', 'Tidak')], default='Terdownload', max_length=15, verbose_name='Rekaman Gangguan Terdownload'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='software_config',
            field=models.CharField(blank=True, choices=[('Terdownload', 'Terdownload'), ('Tidak', 'Tidak')], default='Terdownload', max_length=15, verbose_name='Software/Config Terdownload'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='tergrounding',
            field=models.CharField(blank=True, choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], default='Ya', max_length=5, verbose_name='Tergrounding'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='v_backup',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tegangan Backup (VDC)'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='v_input_power',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tegangan Input Power (VDC)'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='visual_5r',
            field=models.CharField(blank=True, choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Kurang Baik', 'Kurang Baik'), ('Jelek', 'Jelek')], default='Baik', max_length=15, verbose_name='Visual & 5R'),
        ),
        migrations.AlterField(
            model_name='maintenancedfr',
            name='waktu_dfr',
            field=models.CharField(blank=True, choices=[('Sesuai', 'Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai')], default='Sesuai', max_length=30, verbose_name='Pengecekan Waktu DFR'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='alarm',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='catatan',
            field=models.TextField(blank=True, verbose_name='Catatan / Saran Perbaikan'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev1_comm',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT', 'NOT')], default='OK', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev1_ready',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('NOT', 'NOT')], default='READY', max_length=5),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev2_comm',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT', 'NOT')], default='OK', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev2_ready',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('NOT', 'NOT')], default='READY', max_length=5),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev3_comm',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT', 'NOT')], default='OK', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev3_ready',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('NOT', 'NOT')], default='READY', max_length=5),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev4_comm',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT', 'NOT')], default='OK', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev4_ready',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('NOT', 'NOT')], default='READY', max_length=5),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev5_comm',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT', 'NOT')], default='OK', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev5_ready',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('NOT', 'NOT')], default='READY', max_length=5),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev6_comm',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT', 'NOT')], default='OK', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='dev6_ready',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('NOT', 'NOT')], default='READY', max_length=5),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='frekuensi',
            field=models.CharField(blank=True, max_length=20, verbose_name='Frekuensi (Hz)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='healthy',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='i_a',
            field=models.CharField(blank=True, max_length=20, verbose_name='I A (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='i_b',
            field=models.CharField(blank=True, max_length=20, verbose_name='I B (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='i_c',
            field=models.CharField(blank=True, max_length=20, verbose_name='I C (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='over_power',
            field=models.CharField(blank=True, max_length=20, verbose_name='Over Power (kV)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='selektor',
            field=models.CharField(blank=True, max_length=50, verbose_name='*Selektor'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='setting_i',
            field=models.CharField(blank=True, max_length=20, verbose_name='I> (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='setting_ii',
            field=models.CharField(blank=True, max_length=20, verbose_name='I>> (A)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='supply_dc',
            field=models.CharField(blank=True, max_length=50, verbose_name='*Supply DC'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='trip_led',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='normal', max_length=20, verbose_name='Trip LED'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='under_power',
            field=models.CharField(blank=True, max_length=20, verbose_name='Under Power (kV)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='v_a',
            field=models.CharField(blank=True, max_length=20, verbose_name='V A (kV)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='v_b',
            field=models.CharField(blank=True, max_length=20, verbose_name='V B (kV)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='v_c',
            field=models.CharField(blank=True, max_length=20, verbose_name='V C (kV)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='waktu_i',
            field=models.CharField(blank=True, max_length=20, verbose_name='Waktu I> (s)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='waktu_ii',
            field=models.CharField(blank=True, max_length=20, verbose_name='Waktu I>> (s)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='waktu_over',
            field=models.CharField(blank=True, max_length=20, verbose_name='Waktu Over (s)'),
        ),
        migrations.AlterField(
            model_name='maintenancemastertrip',
            name='waktu_under',
            field=models.CharField(blank=True, max_length=20, verbose_name='Waktu Under (s)'),
        ),
    ]
