# Generated by Django 6.0.2 on 2026-06-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0045_merge_teleproteksi_main'),
        ('maintenance', '0046_alter_maintenancedfr_catatan_khusus_and_more'),
    ]

    operations = [
    ]
