# Generated by Django 6.0.2 on 2026-06-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0047_maintenancemux_status_tidak_terpasang'),
        ('maintenance', '0047_merge_20260604_1138'),
    ]

    operations = [
    ]
