# Generated by Django 6.0.2 on 2026-06-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0048_alter_maintenancedfr_catatan_khusus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMasterStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spek_merk', models.CharField(blank=True, default='', max_length=100, verbose_name='Merk')),
                ('spek_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Type')),
                ('spek_os', models.CharField(blank=True, default='', max_length=100, verbose_name='Operating System')),
                ('spek_firmware', models.CharField(blank=True, default='', max_length=100, verbose_name='Firmware Version')),
                ('spek_config_ver', models.CharField(blank=True, default='', max_length=100, verbose_name='Configuration Version')),
                ('spek_ip', models.CharField(blank=True, default='', max_length=50, verbose_name='IP Address')),
                ('kondisi_server', models.CharField(blank=True, choices=[('BERSIH', 'Bersih'), ('TIDAK BERSIH', 'Tidak Bersih')], default='', max_length=20, verbose_name='Server / Workstation')),
                ('kondisi_panel', models.CharField(blank=True, choices=[('BERSIH', 'Bersih'), ('TIDAK BERSIH', 'Tidak Bersih')], default='', max_length=20, verbose_name='Panel')),
                ('temp_ruangan', models.FloatField(blank=True, null=True, verbose_name='Temperatur Ruangan (°C)')),
                ('temp_peralatan', models.FloatField(blank=True, null=True, verbose_name='Temperatur Peralatan (°C)')),
                ('kondisi_sebelum', models.CharField(blank=True, choices=[('PC/SB/TR/ON', 'PC / SB / TR / ON'), ('NC/OFF', 'NC / OFF')], default='', max_length=20, verbose_name='Kondisi Sebelum')),
                ('kondisi_sesudah', models.CharField(blank=True, choices=[('PC/SB/TR/ON', 'PC / SB / TR / ON'), ('NC/OFF', 'NC / OFF')], default='', max_length=20, verbose_name='Kondisi Sesudah')),
                ('power_supply', models.CharField(blank=True, choices=[('ADA, BERFUNGSI', 'Ada, Berfungsi'), ('ADA, TIDAK BERFUNGSI', 'Ada, Tidak Berfungsi'), ('TIDAK ADA', 'Tidak Ada')], default='', max_length=30, verbose_name='Power Supply')),
                ('power_supply_jml', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Power Supply')),
                ('fan_processor', models.CharField(blank=True, choices=[('ADA, BERFUNGSI', 'Ada, Berfungsi'), ('ADA, TIDAK BERFUNGSI', 'Ada, Tidak Berfungsi'), ('TIDAK ADA', 'Tidak Ada')], default='', max_length=30, verbose_name='Fan Processor')),
                ('fan_processor_jml', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jumlah Fan Processor')),
                ('cpu_merk', models.CharField(blank=True, default='', max_length=100, verbose_name='CPU Merk/Jumlah')),
                ('ram_merk', models.CharField(blank=True, default='', max_length=100, verbose_name='RAM Merk/Jumlah')),
                ('ram_kapasitas', models.CharField(blank=True, default='', max_length=100, verbose_name='RAM Kapasitas/Terpakai')),
                ('storage_merk', models.CharField(blank=True, default='', max_length=100, verbose_name='Storage Merk/Jumlah')),
                ('storage_kapasitas', models.CharField(blank=True, default='', max_length=100, verbose_name='Storage Kapasitas/Terpakai')),
                ('vga_merk', models.CharField(blank=True, default='', max_length=100, verbose_name='VGA Card Merk')),
                ('vga_kondisi', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], default='', max_length=10, verbose_name='VGA Card Kondisi')),
                ('indikasi_alarm', models.CharField(blank=True, choices=[('ADA', 'Ada'), ('TIDAK ADA', 'Tidak Ada')], default='', max_length=15, verbose_name='Indikasi Alarm/Error')),
                ('time_sync', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], default='', max_length=10, verbose_name='Time Synchronization')),
                ('copper_jumlah', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Copper — Jumlah')),
                ('copper_kondisi', models.CharField(blank=True, choices=[('OK', 'OK'), ('ALARM', 'Alarm')], default='', max_length=10, verbose_name='Copper — Kondisi')),
                ('fo_jumlah', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FO — Jumlah')),
                ('fo_kondisi', models.CharField(blank=True, choices=[('OK', 'OK'), ('ALARM', 'Alarm')], default='', max_length=10, verbose_name='FO — Kondisi')),
                ('komm_1', models.CharField(blank=True, default='', max_length=200, verbose_name='Komunikasi 1')),
                ('komm_2', models.CharField(blank=True, default='', max_length=200, verbose_name='Komunikasi 2')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenancemasterstation', to='maintenance.maintenance')),
            ],
            options={
                'verbose_name': 'Maintenance Master Station',
            },
        ),
    ]
