# Generated by Django 6.0.2 on 2026-06-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0048_merge_20260608_0837'),
        ('maintenance', '0049_maintenancemasterstation'),
    ]

    operations = [
    ]
