# Generated by Django 6.0.2 on 2026-06-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0048_alter_maintenancedfr_catatan_khusus_and_more'),
        ('maintenance', '0050_merge_20260610_2206'),
    ]

    operations = [
    ]
