# Generated by Django 6.0.2 on 2026-06-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0050_merge_20260615_1056'),
        ('maintenance', '0050_beritaacararecord_file_upload'),
    ]

    operations = [
    ]
