# Generated by Django 6.0.2 on 2026-06-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0050_beritaacararecord_file_upload'),
        ('maintenance', '0051_merge_20260615_1058'),
    ]

    operations = [
    ]
