# Generated by Django 6.0.2 on 2026-07-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0052_merge_20260617_1459"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRepeater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suhu_ruangan",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Suhu Ruangan (°C)"
                    ),
                ),
                (
                    "kebersihan",
                    models.CharField(
                        blank=True,
                        choices=[("Bersih", "Bersih"), ("Kotor", "Kotor")],
                        max_length=10,
                    ),
                ),
                (
                    "lampu_penerangan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Menyala", "Menyala"),
                            ("Tidak Menyala", "Tidak Menyala"),
                            ("Redup", "Redup"),
                            ("Tidak Ada", "Tidak Ada"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "ada_radio_tx",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOK", "NOK")],
                        max_length=3,
                        verbose_name="Radio TX",
                    ),
                ),
                (
                    "ada_radio_rx",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOK", "NOK")],
                        max_length=3,
                        verbose_name="Radio RX",
                    ),
                ),
                (
                    "ada_battery",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOK", "NOK")],
                        max_length=3,
                        verbose_name="Battery",
                    ),
                ),
                (
                    "merk_battery",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Merk Battery"
                    ),
                ),
                (
                    "ada_power_supply",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "OK"), ("NOK", "NOK")],
                        max_length=3,
                        verbose_name="Power Supply",
                    ),
                ),
                (
                    "merk_power_supply",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Merk Power Supply"
                    ),
                ),
                (
                    "jenis_antena",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Directional", "Directional"),
                            ("Bidirectional", "Bidirectional"),
                        ],
                        max_length=15,
                        verbose_name="Jenis Antena",
                    ),
                ),
                (
                    "merk_radio_tx",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Merk Radio TX"
                    ),
                ),
                (
                    "tipe_radio_tx",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipe/Model Radio TX"
                    ),
                ),
                (
                    "merk_radio_rx",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Merk Radio RX"
                    ),
                ),
                (
                    "tipe_radio_rx",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipe/Model Radio RX"
                    ),
                ),
                (
                    "tegangan_battery",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tegangan Battery (V)"
                    ),
                ),
                (
                    "tegangan_psu",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tegangan Power Supply (V)"
                    ),
                ),
                (
                    "swr_tx",
                    models.FloatField(blank=True, null=True, verbose_name="SWR TX"),
                ),
                (
                    "power_tx",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Power TX (W)"
                    ),
                ),
                (
                    "frekuensi_tx",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frekuensi TX / Tone (MHz)"
                    ),
                ),
                (
                    "swr_rx",
                    models.FloatField(blank=True, null=True, verbose_name="SWR RX"),
                ),
                (
                    "frekuensi_rx",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Frekuensi RX / Tone (MHz)"
                    ),
                ),
                ("catatan", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "maintenance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Repeater",
            },
        ),
    ]
