# Generated by Django 6.0.2 on 2026-08-04 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0053_maintenancerepeater'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spek_merk', models.CharField(blank=True, default='', max_length=100, verbose_name='Merk')),
                ('spek_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Type')),
                ('spek_cpu', models.CharField(blank=True, default='', max_length=100, verbose_name='CPU')),
                ('spek_firmware', models.CharField(blank=True, default='', max_length=100, verbose_name='Firmware Version')),
                ('spek_config_ver', models.CharField(blank=True, default='', max_length=100, verbose_name='Configuration Version')),
                ('spek_ip', models.CharField(blank=True, default='', max_length=50, verbose_name='Maintenance IP')),
                ('suhu_ruangan', models.FloatField(blank=True, null=True, verbose_name='Suhu Ruangan (°C)')),
                ('suhu_panel', models.FloatField(blank=True, null=True, verbose_name='Suhu dalam Panel (°C)')),
                ('kondisi_cpu', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Tidak Normal', 'Tidak Normal')], default='', max_length=15, verbose_name='Kondisi CPU')),
                ('indikasi_alarm', models.CharField(blank=True, choices=[('Tidak Ada', 'Tidak Ada'), ('Ada', 'Ada')], default='', max_length=15, verbose_name='Indikasi Alarm / Error')),
                ('komunikasi_master', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Tidak Normal', 'Tidak Normal')], default='', max_length=15, verbose_name='Komunikasi ke Master Station')),
                ('tampilan_lcd', models.CharField(blank=True, choices=[('Terang', 'Terang'), ('Kabur', 'Kabur')], default='', max_length=10, verbose_name='Tampilan LCD')),
                ('komunikasi_server', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Tidak Normal', 'Tidak Normal')], default='', max_length=15, verbose_name='Komunikasi ke Server')),
                ('time_sync', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Tidak Normal', 'Tidak Normal')], default='', max_length=15, verbose_name='Time Synchronization')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('ps_jenis', models.CharField(blank=True, choices=[('110 VDC', '110 VDC'), ('48 VDC', '48 VDC')], default='', max_length=10, verbose_name='Jenis Power Supply')),
                ('ps_teg_input', models.FloatField(blank=True, null=True, verbose_name='Tegangan Input (V)')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenancebcu', to='maintenance.maintenance')),
            ],
            options={
                'verbose_name': 'Maintenance BCU',
            },
        ),
    ]
