# Generated by Django 6.0.2 on 2026-08-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0054_maintenancebcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='beritaacararecord',
            name='columns_data',
            field=models.JSONField(blank=True, default=list, help_text='Header kolom custom untuk BA generik (lainnya/penormalan). Kosong untuk jenis dengan template tetap.'),
        ),
        migrations.AddField(
            model_name='beritaacararecord',
            name='jenis_lain',
            field=models.CharField(blank=True, help_text="Label kategori custom saat jenis='lainnya'.", max_length=200, verbose_name='Kategori Lain'),
        ),
    ]
