# Generated by Django 6.0.2 on 2026-08-07 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0061_db_indexes'),
        ('maintenance', '0055_beritaacararecord_columns_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['device', 'status', '-date'], name='maint_dev_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['status', '-date'], name='maint_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['maintenance_type', '-date'], name='maint_type_date_idx'),
        ),
    ]
