# Generated by Django 6.0.2 on 2026-08-07 01:10

import django.core.validators
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0056_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritaacararecord',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Dokumen BA yang sudah jadi (hasil upload langsung, tanpa generate PDF)', null=True, upload_to=maintenance.models.ba_file_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx']), maintenance.models.validate_ba_file_size], verbose_name='File BA (Upload)'),
        ),
    ]
