# Generated by Django 6.0.2 on 2026-09-08 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0057_upload_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='beritaacararecord',
            name='sumber_maintenance',
            field=models.ForeignKey(blank=True, help_text='Terisi bila BA ini terbit otomatis dari form pemeliharaan corrective. Dipakai supaya satu perbaikan tidak menerbitkan BA berkali-kali saat formnya disimpan ulang.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita_acara', to='maintenance.maintenance', verbose_name='Terbit dari Pemeliharaan'),
        ),
    ]
