# Generated by Django 6.0.2 on 2026-09-16 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0069_pengumumanpemeliharaan'),
        ('maintenance', '0058_beritaacararecord_sumber_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Dihapus oleh'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Dihapus (soft-delete)'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['is_deleted'], name='maint_is_deleted_idx'),
        ),
    ]
