"""Registry Respons Kit (ekstraksi persis Excel Respons_Kit_2025).
RESPON_PLANTS: nama plant -> [(B1,B3)…] (MW = jumlah unit).
RESPON_GROUPS: (judul kelompok, [nama plant…]) — 1 chart per grup, spt PDF Excel."""

RESPON_PLANTS = {
    'A_POSO 11': [['SLWNA6', 'UNIT1_P']],
    'A_POSO 12': [['SLWNA6', 'UNIT2_P']],
    'A_POSO 13': [['SLWNA6', 'UNIT3_P']],
    'A_POSO 14': [['SLWNA6', 'UNIT4_P']],
    'A_POSO 2A1': [['PMONA6', 'UNIT1_P']],
    'A_POSO 2A2': [['PMONA6', 'UNIT2_P']],
    'A_POSO 2A3': [['PMONA6', 'UNIT3_P']],
    'A_POSO 2B1': [['PMONA6', 'UNIT4_P']],
    'A_POSO 2B2': [['PMONA6', 'UNIT5_P']],
    'A_POSO 2B3': [['PMONA6', 'UNIT6_P']],
    'A_POSO 2B4': [['PMONA6', 'UNIT7_P']],
    'A_BAKARU 1': [['BKARU5', 'UNIT1_P']],
    'A_BAKARU 2': [['BKARU5', 'UNIT2_P']],
    'A_MALEA 1': [['MALEA5', 'UNIT1_P']],
    'A_MALEA 2': [['MALEA5', 'UNIT2_P']],
    'A_BILIBILI': [['PBILI', 'UNIT1_P'], ['PBILI', 'UNIT2_P']],
    'A_TRSBR': [['PLTMH', 'UNIT1_P']],
    'U_PGAYA 1': [['PNGYA5', 'UNIT1_P']],
    'U_PGAYA 2': [['PNGYA5', 'UNIT2_P']],
    'U_JNPTO 1': [['PJPNT1', 'UNIT1_P']],
    'U_JNPTO 2': [['PJPNT1', 'UNIT2_P']],
    'U_JNPTO 3A': [['PJNPT2', 'UNIT1_P']],
    'U_JNPTO 3B': [['PJNPT2', 'UNIT2_P']],
    'U_BARRU 1': [['BLUSU5', 'UNIT1_P']],
    'U_BARRU 2': [['BLUSU5', 'UNIT2_P']],
    'U_SB2': [['BLUSU5', 'UNIT3_P']],
    'U_NII TANASA': [['NTNSA4', 'UNIT3_P'], ['NTNSA4', 'UNIT4_P'], ['NTNSA4', 'UNIT5_P']],
    'U_MORAMO 1': [['KNDI35', 'UNIT1_P']],
    'U_MORAMO 2': [['KNDI35', 'UNIT2_P']],
    'U_MAMUJU': [['PMMJU', 'UNIT1_P'], ['PMMJU', 'UNIT2_P']],
    'U_PALU 31': [['PPLU35', 'UNIT1_P']],
    'U_PALU 32': [['PPLU35', 'UNIT2_P']],
    'G_SKG GT 11': [['SKANG5', 'UNIT1_P']],
    'G_SKG GT 12': [['SKANG5', 'UNIT2_P']],
    'G_SKG ST 18': [['SKANG5', 'UNIT3_P']],
    'G_SKG GT 21': [['SKANG5', 'UNIT4_P']],
    'G_SKG GT 22': [['SKANG5', 'UNIT5_P']],
    'G_SKG ST 28': [['SKANG5', 'UNIT6_P']],
    'D_SUPPA': [['SUPPA5', 'UNIT1_P'], ['SUPPA5', 'UNIT2_P']],
    'MG_KENDARI': [['NTNSA4', 'UNIT1_P'], ['NTNSA4', 'UNIT2_P']],
    'G_GE': [['TELLO5', 'UNIT3_P'], ['TELLO5', 'UNIT4_P']],
    'D_TELLO': [['TELLO5', 'UNIT5_P'], ['TELLO5', 'UNIT6_P'], ['TELLO5', 'UNIT1_P'], ['TELLO5', 'UNIT2_P']],
    'D_SILAE': [['PLTD_SILAE', 'UNIT1_P']],
    'D_TALLOLAMA': [['TLAMA_SW', 'UNIT1_P'], ['TLAMA_SW', 'UNIT2_P']],
    'D_PGAYA': [['PNGYA5_SW', 'UNIT1_P'], ['PNGYA5_SW', 'UNIT2_P']],
    'D_TELLO (SEWA)': [['TELLO_SW', 'UNIT1_P'], ['TELLO_SW', 'UNIT2_P']],
    'MPP_SUPPA': [['SUPPA5', 'UNIT3_P']],
    'MPP_TELLO': [['TELLO_SW', 'UNIT4_P']],
    'MPP_PGAYA': [['PNGYA5_SW', 'UNIT3_P']],
    'B_TOLO': [['PLTBT', 'UNIT1_P'], ['PLTBT', 'UNIT2_P']],
    'B_SIDRAP': [['PLTBS', 'UNIT1_P'], ['PLTBS', 'UNIT2_P']],
}

RESPON_GROUPS = [
    ('PLTA Poso 2A', ['A_POSO 2A1', 'A_POSO 2A2', 'A_POSO 2A3']),
    ('PLTA Poso 1', ['A_POSO 11', 'A_POSO 12', 'A_POSO 13', 'A_POSO 14']),
    ('PLTA Poso 2B', ['A_POSO 2B1', 'A_POSO 2B2', 'A_POSO 2B3', 'A_POSO 2B4']),
    ('PLTA Bakaru', ['A_BAKARU 1', 'A_BAKARU 2']),
    ('PLTA Malea', ['A_MALEA 1', 'A_MALEA 2']),
    ('PLTA Tersebar', ['A_BILIBILI', 'A_TRSBR']),
    ('PLTU Punagaya', ['U_PGAYA 1', 'U_PGAYA 2']),
    ('PLTU Jeneponto Eksisting', ['U_JNPTO 1', 'U_JNPTO 2']),
    ('PLTU Jeneponto Ekspansi', ['U_JNPTO 3A', 'U_JNPTO 3B']),
    ('PLTU Sulsel Barru 2', ['U_SB2']),
    ('PLTU Barru', ['U_BARRU 1', 'U_BARRU 2']),
    ('PLTU Nii Tanasa', ['U_NII TANASA']),
    ('PLTU Moramo', ['U_MORAMO 1', 'U_MORAMO 2']),
    ('PLTU Mamuju', ['U_MAMUJU']),
    ('PLTU Palu 3', ['U_PALU 32', 'U_PALU 31']),
    ('PLTGU Sengkang Blok 1', ['G_SKG GT 11', 'G_SKG GT 12', 'G_SKG ST 18']),
    ('PLTGU Sengkang Blok 2', ['G_SKG GT 21', 'G_SKG GT 22', 'G_SKG ST 28']),
    ('Thermal BBM #1', ['D_SUPPA', 'MG_KENDARI', 'G_GE']),
    ('Thermal BBM #2', ['D_TELLO', 'D_SILAE']),
    ('Thermal BBM #3', ['D_TALLOLAMA', 'D_PGAYA', 'D_TELLO (SEWA)']),
    ('Thermal BBM #4', ['MPP_SUPPA', 'MPP_TELLO', 'MPP_PGAYA']),
    ('VRE', ['B_TOLO', 'B_SIDRAP']),
]
