from django.urls import path
from . import views

urlpatterns = [
    path('',              views.dashboard,         name='opsis_dashboard'),
    path('up2d/',         views.up2d,              name='opsis_up2d'),
    path('<int:pk>/',     views.pembangkit_detail, name='opsis_pembangkit'),
    path('api/live/',     views.api_live,          name='opsis_api_live'),
    path('api/trend/<int:pk>/', views.api_trend,   name='opsis_api_trend'),
    path('api/freq/',            views.api_freq,     name='opsis_api_freq'),
    path('api/beban/',           views.api_beban,       name='opsis_api_beban'),
    path('api/hz/',              views.api_hz,          name='opsis_api_hz'),
    path('api/hz-sultra/',       views.api_hz_sultra,   name='opsis_api_hz_sultra'),
    path('api/hz-baubau/',       views.api_hz_baubau,   name='opsis_api_hz_baubau'),
    path('api/hz-sulteng/',      views.api_hz_sulteng,  name='opsis_api_hz_sulteng'),
    path('api/hz-luwuk/',        views.api_hz_luwuk,    name='opsis_api_hz_luwuk'),
    path('api/ping/',            views.api_ping,     name='opsis_api_ping'),
    path('api/diagnose/',       views.api_diagnose, name='opsis_api_diagnose'),
    path('api/history/<int:pk>/', views.api_history,        name='opsis_api_history'),
    path('export/frekuensi/',     views.export_frekuensi,   name='opsis_export_frekuensi'),
    path('export/beban/',         views.export_beban,        name='opsis_export_beban'),
    path('rangkuman/',            views.rangkuman,           name='opsis_rangkuman'),
    path('beban-trafo/',          views.beban_trafo,         name='opsis_beban_trafo'),
    path('api/beban-trafo/',      views.api_beban_trafo,     name='opsis_api_beban_trafo'),
    path('beban-trafo-chart/',      views.beban_trafo_chart,      name='opsis_beban_trafo_chart'),
    path('api/beban-trafo-chart/',  views.api_beban_trafo_chart,  name='opsis_api_beban_trafo_chart'),
    path('beban-trafo-ibt/',      views.beban_trafo_ibt,     name='opsis_beban_trafo_ibt'),
    path('api/beban-trafo-ibt/',  views.api_beban_trafo_ibt, name='opsis_api_beban_trafo_ibt'),
    path('beban-ktt/',            views.beban_ktt,           name='opsis_beban_ktt'),
    path('api/beban-ktt/',        views.api_beban_ktt,       name='opsis_api_beban_ktt'),
]
