# This is site settings which can only be updated offline before program is running
# For more information, visit https://nicegui.io/documentation/section_configuration_deployment

import platform
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional


__doc__ = """
SCADA Availability
Aplikasi yang digunakan untuk penghitungan availability SCADA pada bagian Fasilitas Operasi PLN UP2B Sistem Makassar.

OPTIONS
-d	--dark			whether to use Quasar's dark mode (default: False, use None for "auto" mode)
-f	--favicon		relative filepath, absolute URL to a favicon (default: None, NiceGUI icon will be used)
					or emoji (e.g. '🚀', works for most browsers)
-h	--help			show this help message
-i	--host			start server with this host (defaults to '127.0.0.1' in native mode, otherwise '0.0.0.0')
-o	--on-air		tech preview: allows temporary remote access if set to True (default: disabled)
-p	--port			used port (default: 8080 in normal mode, and an automatically determined open port in native mode)
-r	--reload		automatically reload the UI on file changes (default: True)
	--no-reload		prevent reload the UI on file changes
-s	--show			automatically open the UI in a browser tab (default: True)
	--no-show		prevent open the UI in a browser tab
-t	--title			page title
	--viewport		page meta viewport content (default: 'width=device-width, initial-scale=1',
					can be overwritten per page)
	--reconnect-timeout			maximum time the server waits for the browser to reconnect (default: 3.0 seconds)
	--endpoint-documentation	control what endpoints appear in the autogenerated OpenAPI docs
								(default: 'none', options: 'none', 'internal', 'page', 'all')
	--show-welcome-message		whether to show the welcome message (default: True)
"""

BASE_DIR = Path(__file__).parent.parent.resolve()
APP_DIR = Path(__file__).parent.resolve()
CONFIG_DIR = BASE_DIR / 'availability/src'
HOST: str = '0.0.0.0'
PORT: int = 8001

APP_TITLE: str = 'Aplikasi Availability SCADA'
VIEWPORT: str = 'width=device-width, initial-scale=1'
FAVICON: Optional[str] = None

DEBUG: bool = False
AUTO_SHOW: bool = True
AUTO_RELOAD: bool = False

ON_AIR: bool = False
ENDPOINT_DOCUMENTATION: Literal['none', 'internal', 'page', 'all'] = 'none'

BINDING_REFRESH_INTERVAL: float = 0.3
MAX_PROPAGATION_TIME: float = 0.05	 # default 0.01
MAX_CPU_USAGE: int = 8
RECONNECT_TIMEOUT: float = 3.0


PY_VERSION = platform.python_version()
PY_NODE = platform.node()
HEAD_HTML_SOURCES: List[str] = [
	'head.html'
]

ARGS_OPTIONS: List[Dict[str, Any]] = [
    {
        'flags': ('-i', '--host'),
		'help': 'start server with this host (defaults to "127.0.0.1" in native mode, otherwise "0.0.0.0")'
	},
	{
		'flags': ('-p', '--port'),
		'help': 'used port (default: 8080 in normal mode, and an automatically determined open port in native mode)',
		'type': int
	},
	{
		'flags': ('-t', '--title'),
		'help': 'page title'
	},
	{
		'flags': ('-f', '--favicon'),
		'help': 'relative filepath, absolute URL to a favicon (default: None, NiceGUI icon will be used) or emoji (e.g. "🚀", works for most browsers)'
	},
	{
		'flags': ('-d', '--dark'),
		'help': 'whether to use Quasar\'s dark mode (default: False, use None for "auto" mode)',
		'default': False,
		'action': 'store_true'
	},
	{
		'flags': ('-o', '--on-air'),
		'help': 'tech preview: allows temporary remote access if set to True (default: disabled)',
		'action': 'store_true'
	},
	{
		'flags': ('-r', '--reload'),
		'help': 'automatically reload the UI on file changes',
		'action': 'store_true'
	},
	{
		'flags': ('--no-reload',),
		'help': 'prevent reload the UI on file changes',
		'action': 'store_false'
	},
	{
		'flags': ('-s', '--show'),
		'help': 'automatically open the UI in a browser tab',
		'action': 'store_true'
	},
	{
		'flags': ('--no-show',),
		'help': 'prevent open the UI in a browser tab',
		'action': 'store_false'
	}
]