# Generated by Django 6.0.2 on 2026-07-10 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Judul / Lokasi Pemeliharaan",
                    ),
                ),
                (
                    "stream_key",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Token Publish Video",
                    ),
                ),
                (
                    "pengawas_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="Token Publish Talkback",
                    ),
                ),
                (
                    "view_token",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Token Baca Video",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("live", "Live"), ("ended", "Selesai")],
                        default="live",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pengawas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sessions_pengawas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengawas (AM)",
                    ),
                ),
                (
                    "teknisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teknisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesi Live Streaming",
                "verbose_name_plural": "Sesi Live Streaming",
                "ordering": ["-started_at"],
            },
        ),
    ]
