# Generated by Django 6.0.2 on 2026-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="recording_path",
            field=models.CharField(
                blank=True, editable=False, max_length=500, verbose_name="Path Rekaman"
            ),
        ),
    ]
