# Generated by Django 6.0.2 on 2026-09-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_livesession_talkback_recording_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzvizToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Ezviz',
                'verbose_name_plural': 'Token Ezviz',
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='sumber',
            field=models.CharField(choices=[('perangkat', 'Kamera HP / Laptop'), ('ezviz', 'Kamera CCTV Ezviz')], default='perangkat', max_length=10, verbose_name='Sumber Video'),
        ),
        migrations.CreateModel(
            name='KameraEzviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Kamera')),
                ('serial', models.CharField(help_text='Device serial di akun Ezviz, mis. BD3957004', max_length=64, verbose_name='Serial Perangkat')),
                ('channel', models.PositiveSmallIntegerField(default=1, help_text='Nomor channel kamera. NVR punya banyak channel; kamera tunggal biasanya 1.', verbose_name='Channel')),
                ('lokasi', models.CharField(blank=True, max_length=150, verbose_name='Lokasi / Gardu Induk')),
                ('hd', models.BooleanField(default=True, help_text='Nonaktifkan kalau jaringan lokasi lemah — kualitas turun, tapi lebih jarang buffering.', verbose_name='Putar Kualitas HD')),
                ('aktif', models.BooleanField(default=True, help_text='Hanya kamera aktif yang muncul di pilihan sumber saat memulai live.', verbose_name='Aktif')),
                ('keterangan', models.CharField(blank=True, max_length=250, verbose_name='Keterangan')),
                ('status_cloud', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Status di Cloud Ezviz')),
                ('terakhir_sinkron', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Terakhir Disinkronkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kamera CCTV Ezviz',
                'verbose_name_plural': 'Kamera CCTV Ezviz',
                'ordering': ['lokasi', 'nama'],
                'unique_together': {('serial', 'channel')},
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='kamera',
            field=models.ForeignKey(blank=True, help_text='Hanya dipakai kalau sumber = Kamera CCTV Ezviz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesi', to='streaming.kameraezviz', verbose_name='Kamera CCTV Ezviz'),
        ),
    ]
