# Generated by Django 6.0.2 on 2026-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_ezviztoken_livesession_sumber_kameraezviz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='publisher_last_seen',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Penyiar Terakhir Terlihat'),
        ),
    ]
