# Generated by Django 6.0.2 on 2026-09-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_livesession_publisher_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezviztoken',
            name='area_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domain Region dari Ezviz'),
        ),
    ]
