# Generated by Django 6.0.2 on 2026-09-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_ezviztoken_area_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='kameraezviz',
            name='kode_verifikasi',
            field=models.CharField(blank=True, help_text='Wajib diisi kalau enkripsi video kamera masih aktif (bawaan pabrik EZVIZ). Kodenya tercetak di stiker badan kamera dan terlihat di aplikasi EZVIZ. Kosongkan kalau enkripsi sudah dimatikan dari aplikasi EZVIZ.', max_length=32, verbose_name='Kode Verifikasi Perangkat'),
        ),
    ]
