# Generated by Django 6.0.2 on 2026-09-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_kameraezviz_kode_verifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanEzviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(blank=True, help_text='Dari console Ezviz Open Platform. Kosong = pakai EZVIZ_APP_KEY di .env.', max_length=128, verbose_name='appKey')),
                ('app_secret', models.CharField(blank=True, help_text='Kosong = pakai EZVIZ_APP_SECRET di .env.', max_length=128, verbose_name='appSecret')),
                ('api_base', models.CharField(blank=True, help_text='Mis. https://isgpopen.ezvizlife.com. Kosong = pakai EZVIZ_API_BASE di .env. Region persisnya tetap ditentukan Ezviz sendiri lewat areaDomain.', max_length=200, verbose_name='Host API')),
                ('ezopen_host', models.CharField(blank=True, help_text='Kosong = disimpulkan otomatis (open.ys7.com untuk platform Tiongkok, open.ezviz.com untuk yang lain). Isi hanya kalau manage.py cek_ezviz menemukan host lain yang diterima.', max_length=200, verbose_name='Host di alamat ezopen')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Ezviz',
                'verbose_name_plural': 'Pengaturan Ezviz',
            },
        ),
    ]
