# Generated by Django 6.0.2 on 2026-04-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama RTU')),
                ('lokasi', models.CharField(blank=True, max_length=100, verbose_name='Lokasi / Gardu')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('state', models.CharField(default='UNKNOWN', max_length=10, verbose_name='State')),
                ('state_sejak', models.DateTimeField(blank=True, null=True, verbose_name='State Sejak')),
            ],
            options={
                'verbose_name': 'RTU',
                'verbose_name_plural': 'RTU',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='RTULog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('mulai', models.DateTimeField(db_index=True)),
                ('selesai', models.DateTimeField(blank=True, null=True)),
                ('durasi_menit', models.PositiveIntegerField(blank=True, null=True)),
                ('rtu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='device_mon.rtu')),
            ],
            options={
                'verbose_name': 'Log State RTU',
                'verbose_name_plural': 'Log State RTU',
                'ordering': ['-mulai'],
                'indexes': [models.Index(fields=['rtu', '-mulai'], name='device_mon__rtu_id_e9eece_idx')],
            },
        ),
    ]
