# Generated by Django 6.0.2 on 2026-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_mon', '0002_rtualertlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtu',
            name='wa_alert',
            field=models.BooleanField(default=True, help_text='Kirim Early Warning WA saat RTU ini DOWN/pulih. Hilangkan centang untuk membisukan satu RTU tanpa menonaktifkannya dari monitoring.', verbose_name='Blast WhatsApp'),
        ),
    ]
