# Generated by Django 6.0.2 on 2026-08-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_mon", "0003_zabbixhost_zabbixwebhooklog_zabbixeventlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="zabbixhost",
            name="groups",
            field=models.CharField(
                blank=True,
                help_text="Host Group Zabbix tempat host ini terdaftar (dipisah koma bila lebih dari satu), diperbarui otomatis oleh sync_zabbix. Dipakai untuk mengelompokkan tampilan per grup (VoIP Mks, CRS, ROIP, Router, dst — lihat ZABBIX_HOST_GROUPS).",
                max_length=255,
                verbose_name="Grup Zabbix",
            ),
        ),
    ]
