# Generated by Django 6.0.2 on 2026-08-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_mon", "0004_zabbixhost_groups"),
        ("devices", "0064_add_asset_id_and_open_status_aset"),
    ]

    operations = [
        # RemoveField + AddField, BUKAN AlterField — kolom lama (CharField)
        # berisi string kosong '' (bukan NULL) untuk baris yang belum diisi,
        # dan Postgres tidak bisa CAST '' langsung ke bigint (kolom FK baru)
        # lewat USING clause yang di-generate AlterField. Drop lalu buat ulang
        # kolomnya sekaligus menghindari masalah cast itu — aman karena field
        # lama ini belum pernah benar-benar dipakai (Zabbix API tidak
        # menyediakan data lokasi, field cuma diisi manual).
        migrations.RemoveField(
            model_name="zabbixhost",
            name="lokasi",
        ),
        migrations.AddField(
            model_name="zabbixhost",
            name="lokasi",
            field=models.ForeignKey(
                blank=True,
                help_text="Dari master data Lokasi Site FASOP (devices.SiteLocation) — supaya penamaan lokasi konsisten dengan Device dan halaman lain, bukan diketik bebas.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zabbix_hosts",
                to="devices.sitelocation",
                verbose_name="Lokasi / Gardu",
            ),
        ),
    ]
