# Generated by Django 6.0.2 on 2026-08-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device_mon", "0005_alter_zabbixhost_lokasi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zabbixhost",
            options={
                "ordering": ["urutan", "nama", "pk"],
                "verbose_name": "Host Zabbix",
                "verbose_name_plural": "Host Zabbix",
            },
        ),
    ]
