# Generated by Django 6.0.2 on 2026-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_mon", "0006_alter_zabbixhost_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZabbixGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        help_text="Contoh: VoIP Mks, CRS, ROIP, Router, VoIP Baubau, VoIP ICON+, VoIP Luwuk",
                        max_length=100,
                        unique=True,
                        verbose_name="Nama Grup",
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Nonaktifkan untuk menyembunyikan grup dari dashboard tanpa menghapusnya.",
                        verbose_name="Aktif",
                    ),
                ),
                ("keterangan", models.TextField(blank=True, verbose_name="Keterangan")),
                (
                    "hosts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pilih host Zabbix yang masuk grup ini. Satu host boleh masuk beberapa grup.",
                        related_name="manual_groups",
                        to="device_mon.zabbixhost",
                        verbose_name="Host yang tergabung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grup Host Zabbix",
                "verbose_name_plural": "Grup Host Zabbix",
                "ordering": ["urutan", "nama"],
            },
        ),
    ]
