# Generated by Django 6.0.2 on 2026-09-15 01:47

import device_mon.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_mon', '0008_rtu_wa_alert_zabbixhost_wa_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.SlugField(help_text='Dipakai di URL, mis. "telkom" -> /device-mon/zabbix/telkom/. Huruf kecil, angka, atau strip.', max_length=30, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(help_text='Ditampilkan di menu & judul halaman, mis. "Zabbix Telkom".', max_length=80, verbose_name='Nama Tampilan')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan untuk menyembunyikan dari sidebar dan melewati instansi ini di sync_zabbix, tanpa menghapus datanya.', verbose_name='Aktif')),
                ('api_url', models.CharField(blank=True, default='', help_text='mis. http://zabbix.local/api_jsonrpc.php', max_length=255, verbose_name='URL API')),
                ('api_token', models.CharField(blank=True, default='', max_length=255, verbose_name='API Token')),
                ('api_user', models.CharField(blank=True, default='', max_length=100, verbose_name='Username')),
                ('api_password', models.CharField(blank=True, default='', max_length=255, verbose_name='Password')),
                ('api_timeout', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (detik)')),
                ('host_groups', models.CharField(blank=True, default='', help_text='Opsional, pisahkan koma bila lebih dari satu. Kosong = semua host aktif di server ini.', max_length=255, verbose_name='Filter Host Group')),
                ('webhook_token', models.CharField(blank=True, default='', help_text='Kosong = jatuh ke ZABBIX_WEBHOOK_TOKEN di .env. Isi sendiri kalau instansi ini perlu token berbeda dari instansi lain.', max_length=255, verbose_name='Token Webhook')),
                ('wa_chat_ids', models.CharField(blank=True, default='', help_text='chatId tujuan default untuk seluruh host instansi ini (pisahkan koma). Kosong = jatuh ke WA_CHAT_IDS_ZABBIX lalu WA_CHAT_IDS di .env. Host bisa menimpa lagi lewat kolom "Grup WA Khusus" miliknya sendiri.', max_length=255, verbose_name='Tujuan WA Default')),
            ],
            options={
                'verbose_name': 'Instansi Zabbix',
                'verbose_name_plural': 'Instansi Zabbix',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AlterField(
            model_name='zabbixgroup',
            name='hosts',
            field=models.ManyToManyField(blank=True, help_text='Pilih host Zabbix yang masuk grup ini. Satu host boleh masuk beberapa grup. Pilih host dari instansi Zabbix yang sama dengan grup ini.', related_name='manual_groups', to='device_mon.zabbixhost', verbose_name='Host yang tergabung'),
        ),
        migrations.AlterField(
            model_name='zabbixgroup',
            name='nama',
            field=models.CharField(help_text='Contoh: VoIP Mks, CRS, ROIP, Router, VoIP Baubau, VoIP ICON+, VoIP Luwuk', max_length=100, verbose_name='Nama Grup'),
        ),
        migrations.AlterField(
            model_name='zabbixhost',
            name='zabbix_hostid',
            field=models.CharField(help_text='Kolom "hostid" dari Zabbix API — unik PER INSTANSI (dua server Zabbix berbeda boleh memakai hostid yang sama untuk host yang berbeda).', max_length=50, verbose_name='Host ID Zabbix'),
        ),
        migrations.AddField(
            model_name='zabbixgroup',
            name='instance',
            field=models.ForeignKey(default=device_mon.models._default_zabbix_instance_id, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='device_mon.zabbixinstance', verbose_name='Instansi Zabbix'),
        ),
        migrations.AddField(
            model_name='zabbixhost',
            name='instance',
            field=models.ForeignKey(default=device_mon.models._default_zabbix_instance_id, help_text='Server Zabbix asal host ini (mis. Telkom / Prosis).', on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='device_mon.zabbixinstance', verbose_name='Instansi Zabbix'),
        ),
        migrations.AddField(
            model_name='zabbixwebhooklog',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='Instansi yang dituju URL webhook-nya — bisa kosong bila kode instansi di URL tidak dikenali (lihat Keterangan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='device_mon.zabbixinstance', verbose_name='Instansi Zabbix'),
        ),
        migrations.AlterUniqueTogether(
            name='zabbixgroup',
            unique_together={('instance', 'nama')},
        ),
        migrations.AlterUniqueTogether(
            name='zabbixhost',
            unique_together={('instance', 'zabbix_hostid')},
        ),
    ]
