# Generated by Django 6.0.2 on 2026-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_mon', '0009_zabbixinstance_alter_zabbixgroup_hosts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbixhost',
            name='wa_alert',
            field=models.BooleanField(default=False, help_text='Centang agar transisi PROBLEM/pulih host ini dikirim ke grup WhatsApp lewat WAHA. Butuh WA_ALERT_ENABLED=True di .env.', verbose_name='Blast WhatsApp'),
        ),
    ]
