# Generated by Django 6.0.2 on 2026-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='lokasi_penyimpanan',
            field=models.CharField(help_text='Contoh: Rak B3, Laci 2 Lemari Komponen', max_length=150, verbose_name='Lokasi di Gudang'),
        ),
    ]
