# Generated by Django 6.0.2 on 2026-08-07 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0061_db_indexes'),
        ('gangguan', '0012_db_indexes'),
        ('gudang', '0004_sparepart_tipe_item_jenis_perangkat'),
        ('maintenance', '0056_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mutasisparepart',
            index=models.Index(fields=['sparepart', 'tipe'], name='mutasi_sparepart_tipe_idx'),
        ),
        migrations.AddIndex(
            model_name='mutasisparepart',
            index=models.Index(fields=['tipe'], name='mutasi_tipe_idx'),
        ),
    ]
